BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
BBBBB BBBBB
            XXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXX gettext(u'Register Wallet')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB
BBBBB BBBBBBBBBB
            XXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX X  gettext(u'finances') XXXXXXXXX
BBBBBBBB
XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXX XXXXXX gettext(u'Fill in your wallet data') XXXXX
                XXXXXX
                XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Wallet Holders Name') XXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                            BBBBBBBBBB
                            FFFFFF
                        XXXXXXX
                        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXXXX gettext(u'Send')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Stela Payments') XXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXX XXXXXX gettext(u'Terms and conditions') XXXXX
                XXXXXX
                XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXX
                            
                            XXX XXXXXXXXXXXXXXXXXXXXX
        
                            XXXXX
                        XXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB