BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
BBBBB BBBBB
            XXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXX gettext(u'Withdrawals')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB
BBBBB BBBBBBBBBB
            XXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX X  gettext(u'finances') XXXXXXXXX
BBBBBBBB
XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXX XXXXXX gettext(u'Withdraw Request') XXXXX
                XXXXXX
                XXXX XXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXXXXXX
                        XXXX gettext(u'Receiving account') XXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXX XXXXXX gettext(u'Bank Holder') X   XXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXX XXXXXX gettext(u'ending in')  FFFFFFFFFFFXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXX
                        XXXX gettext(u'Budget amount') XXXXX
                        XXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
                            XXXXXXX XXXXXXXXXX XXXXXXXX XXXX XXXXXXX XXXXX XXXXXXXXXX  gettext(u'Withdraw')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXX XXXX XXXXXXXXX gettext(u'Stela Payments') XXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXX XXXXXX gettext(u'Withdraw conditions') XXXXX
                XXXXXX
                XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXXXXXX
        
                            XXXXX
                        XXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB