BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBBBBBBX XXXXXXXXXXXX XXXXXXXXBBBBBBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXX
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBB
                    BBB BBBBBBB BB BBBBBBBB
                        XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX
                        XXXXXX
                    BBBBBB
                BBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX
               XXXXXX XXXXX XXXXXXXX XX XXXXXX XXXXXXXXXXX XXXX XX XXXXXXXXXX XX XX XXXXXXXXXXX 
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB