BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBBBBBBX XXXXXXXX XXXXXXBBBBBBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXX
                XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBB
                        BBB BBBBBBB BB BBBBBBBB
                            XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXX
                            XXXXXX
                        BBBBBB
                    BBBBB
            XXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXX XXX XXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
                BBBBBBBBBB
                XXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XX XXXXXXXXXXX
                XX XXXXXXXXXXXXXXXX XXXXXXX X XX XXXXXX XXXXX XX XX XXXXXXXXXX
                FFFFFFFFFFFFFFFF
                BB BBBBBBBBBBB
                XXXXXX XXXXX XXXXXXX XXX XXXXXXXXXXX
                BBB BBBBB BB BBBB
                BB BBBBBBBBBBBB
                XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                    X FFFFFFFFF
                XXXXXX
                BBBBB
                BBBBBB
                BBBBB
                XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXX
                
                XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXX
                
                XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX
                XXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXX XXXXXXXXXXX
                XX XXXXX X XXXXXXXXXX XXXXXXXXXXXXX X XXX XXXXXXXX XXXXXXX
                XXXXXXXX
                
                XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXX
                
                XXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXX XXXXXXX XX XXXXXXBBB BBBBBBBBBBBBBBBB XXXXXXXX XXXXXXXXXX
                XXXX
            XXXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB