BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBBB

BBBBBBBB
BBBBB BBBBB
            XXX XXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXX gettext(u'Postulations')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB
BBBBB BBBBBBBBBB
            XXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'CONTROL DYNAMIC')  X  gettext(u'Communications') XXXXXXXXX
BBBBBBBB
BBBBB BBBBBBBBBB
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX gettext(u'Remove')  XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
BBBBBBBB
BBBBB BBBBBBBBB
        XXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXX XXXXXX gettext(u'Jobs List') XXXXX
BBBBBBBB

BBBBB BBBBB
    XXX XXXXXXXXXXXXX XXXXXXXXXXXX
    XXX XXXXXXXXXXXXX XXXXXX gettext(u'Email') XXXXX
    XXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Position Applied') XXXXX
    XXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Salary Expectations') XXXXX
    XXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Availability') XXXXX
    XXX XXXXXXXXXXXXX XXXXXX gettext(u'View') XXXXX
    XXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX  XXXXXXX XXXXXXXXXXXXXXXXX          
BBBBBBBB 
BBBBB BBBBB
    BBB BBBB BB BBBB
        XXXX
            XXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
    BBBBBB
BBBBBBBB




