BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXX
            
            XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
        
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
        
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
        
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXX  gettext(u'Billing type')  XXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXX XXXXXXXXX gettext(u'Billing receipt') XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXX XXXXXXXX gettext(u'Monthly Charges') XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXX gettext(u'Others') XXXXXXXXX
        XXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
         FFFFFFFFFFFFFFF
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXX
        
    XXXXXX
