BBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX

XXXXXX
	XXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
		XXXXXXX
			X X
				XXXXXXXXXXX XXXXXXXXXXX
			X
		
			XXXX X
				XXXXXXX XX
				XXXXXXXX XX
			X
		
			XXXXXXXXXXXXXXXXXXXXXXXXX X
				XXXXXX XXXXXXX XXXXXXXXXXX
				XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
			X
		
			XXXXXXXXXXXXXXXX X X
				XXXXXX XXXXXXXX
				XXXXXXXXXXXXXXXX XXXXX
			X
			X X
				XXXXXX XXXXXXX XXXXXXXXXXX
				XXXXXXXXXXXXXXXX XXXXX
			X
			X X
				XXXXXXXXXXXX XXXXXXX
			X
		
			XXXXXXXXXXXXXX
			XXXXXXXXXXXXX XXXXX X
				XXXXXXXXX XXXX
				XXXXXXXX XXXXX
				XXXXXXXXXXX XXXX
				XXXXXXXXX XXXXXXX
			X
		
			XXXXXXXXXXXX XXXXXXX X
				XXXXXXXX XXXXX
			X
		
			XXXXXX XXXXXXXXXXXXXXXXX X
		
				XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
				XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X
					XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
				X
		
				XXXXXXXXXXXX X
					XXXXXXXXXXX XXXXXXX
				X
		
				XXXXXXXXXXXX XX X
					XXXXXXX X XXXXX
				X
		
				XXXXXXXXXXXX X
					XXXXXXXX XXXXX
				X
		
				XXXXXXXXXXXX X
					XXXXXX XXXX XXXXXXXXXXX
				X
		
				XXXXXX XXXXXXX X
					XXXXXX XXXXX
					XXXXXXXX XXXXXX
				X
		
				XXXXXXXXXXXX X
					XXXXXXXXXXX XX
					XXXXXXXXXXX XX
					XXXXXXXXXX XX
					XXXXXXXXX XXXXXXX
					XXXXXXXXXX XXXX
				X
		
				XXXXXXXXXXXXXX
				XXXXXXXXXXXXX XXXXX X
					XXXXXXXX XXXXX XXXXXXXXXXX
					XXXXXXXXXXX XXXX XXXXXXXXXXX
				X
			X
		XXXXXXXX	
XXXXXXX

XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX XX XXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXX
	XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXX
		XXXXXXX
			XXXX
				XXXX
					XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
						XXXXXXX
							XXXX
								XXXX
									XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XX XXXXXX XXXXX XXXXXX XXXXXX XXXXXXX X XXXXXX XXXXXXXXXXXX
										XXXXXXX
											XXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXX
														XXXX
															XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																BB BBBBBBBBBBBBB BB BBBBBBB BBBBBBB BBBBB
																	XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXX XX XXXXXXXXXX XXXXXX XXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX
																BBBB
																	XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXX XX XXXXXXXXXX XXXXXX XXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX
																BBBBB	
															XXXXX
														XXXXX
													XXXXXXXX
												XXXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXX
														XXXX
															XXX XXXXXXXXXXXX
																BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBB
																	XXX XXXXXXXXXXXXXX XX XXXXXX XXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXX XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'BUDGET') XXXXXXXXXXXX
																BBBB
																	XXX XXXXXXXXXXXXXX XX XXXXXX XXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXX XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'INVOICE') XXXXXXXXXXXX
																BBBBB	
															XXXXX
														XXXXX
													XXXXXXXX
												XXXXX
											XXXXX
										XXXXXXXX
									XXXXXXXX
								XXXXX
							XXXXX
						XXXXXXXX
					XXXXXXXX
					XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
						XXXXXXX
							XXXX
								XXXX
									XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XX XXXXXX XXXXX XXXXXX XXXXXX XXXXXXX X XXXXXX XXXXXXXXXXXX
										XXXXXXX
											XXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXX
														XXXX
															XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXX XXXXXXX XXXX XXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX
																XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXX
																	XXXX
																		XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
																			XXXXXXX XXXXXXXXXXX
																			XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																				XXXX
																					XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXX X XXXXX XXXXXXX XXXXXXXXX
																					XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXX XXXXXXX XXXX XXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
																				XXXXX
																			XXXXXXXX
																		XXXXX
																	XXXXX
																XXXXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
													XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXX
														XXXX
															XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXX XXXXXXX XXXX XXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX
																XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXX
																	XXXX
																		XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
																			XXXXXXX XXXXXXXXXXX
																			XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																				XXXX
																					XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXX X XXXXX XXXXXXX XXXXXXXXX
																					XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXX XXXXXXX XXXX XXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
																				XXXXX
																			XXXXXXXX
																		XXXXX
																	XXXXX
																XXXXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
												XXXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
														XXXX
															XXX XXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																	XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
																XXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
													XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
														XXXX
															XXX XXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																	XX XXXXXXXXXXXXXX XXXXXXXX
																XXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
												XXXXX
											XXXXX
										XXXXXXXX
									XXXXXXXX
								XXXXX
							XXXXX
						XXXXXXXX
					XXXXXXXX
					XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
						XXXXXXX
							XXXX
								XXXX
									XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXX XXXXXX XXXXXX XXXXXXX X XXXXXX XXXXXXXXXXXX
										XXXXXXX
											XXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXX
														XXXX
															XXX XXXXXXXXXXXX
																XXX XXXXXXXXXXXXXX XX XXXXXX XXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Billing Summary') XXXXXXXXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
												XXXXX
											XXXXX
										XXXXXXXX
									XXXXXXXX
								XXXXX
							XXXXX
						XXXXXXXX
					XXXXXXXX
					XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
						XXXXXXX
							XXXX
								XXXX
									XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XX XXXXXX XXXXX XXXXXX XXXXXX XXXXXXX X XXXXXX XXXXXXXXXXXX
										XXXXXXX
											XXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
														XXXX
															XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
																	XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
																		XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																	XXXXXX
																XXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
													BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
														BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
															XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
																XXXX
																	XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																		XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
																			XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
																				XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																			XXXXXX
																		XXXXXX
																	XXXXX
																XXXXX
															XXXXXXXX
														BBBBBB 
													BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
														BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
															XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
																XXXX
																	XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																		XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
																			XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
																				XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																			XXXXXX
																		XXXXXX
																	XXXXX
																XXXXX
															XXXXXXXX
														BBBBBB 
													BBBBB 
												XXXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
														XXXX
															XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
																	XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
																		XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																	XXXXXX
																XXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
													BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
														BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
															XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
																XXXX
																	XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																		XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
																			XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
																				XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																			XXXXXX
																		XXXXXX
																	XXXXX
																XXXXX
															XXXXXXXX
														BBBBBB 
													BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
														BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
															XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
																XXXX
																	XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																		XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
																			XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
																				XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																			XXXXXX
																		XXXXXX
																	XXXXX
																XXXXX
															XXXXXXXX
														BBBBBB 
													BBBBB 		
												XXXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
														XXXX
															XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
																	XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
																		XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Price/ea.') XXXXXXXXXXX
																	XXXXXX
																XXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
													BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
														BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
															XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
																XXXX
																	XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																		XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
																			XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
																				XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																			XXXXXX
																		XXXXXX
																	XXXXX
																XXXXX
															XXXXXXXX
														BBBBBB 
													BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
														BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
															XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
																XXXX
																	XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																		XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
																			XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
																				XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																			XXXXXX
																		XXXXXX
																	XXXXX
																XXXXX
															XXXXXXXX
														BBBBBB 
													BBBBB 
												XXXXX
											XXXXX
										XXXXXXXX
									XXXXXXXX
								XXXXX
							XXXXX
						XXXXXXXX
					XXXXXXXX
					XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
						XXXXXXX
							XXXX
								XXXX
									XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXX XXXXXX XXXXXX XXXXXXX X XXXXXX XXXXXXXXXXXX
										XXXXXXX
											XXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXX
														XXXX
															XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
																	XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXX
																		XXXX
																			XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																		XXXXX
																	XXXXXXXX
																XXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
												XXXXX
											XXXXX
										XXXXXXXX
									XXXXXXXX
								XXXXX
							XXXXX
						XXXXXXXX
					XXXXXXXX
					XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
						XXXXXXX
							XXXX
								XXXX
									XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXX XXXXXX XXXXXX XXXXXXX X XXXXXX XXXXXXXXXXXX
										XXXXXXX
											XXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
												XXXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
														XXXX
															XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
																	XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
																		XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																	XXXXXX
																XXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
												XXXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
														XXXX
															XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
																	XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
																		XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																	XXXXXX
																XXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
												XXXXX
											XXXXX
										XXXXXXXX
									XXXXXXXX
								XXXXX
							XXXXX
						XXXXXXXX
					XXXXXXXX
					XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
						XXXXXXX
							XXXX
								XXXX
									XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXX XXXXXX XXXXXX XXXXXXX X XXXXXX XXXXXXXXXXXX
										XXXXXXX
											XXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
												XXXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
														XXXX
															XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
																	XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
																		XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																	XXXXXX
																XXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
													XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
														XXXX
															XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
																	XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
																		XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																	XXXXXX
																XXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
												XXXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													BB BBBBBBBBBBBBBBBBBBBB
														XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
															XXXX
																XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																	XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
																		XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
																			XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																		XXXXXX
																	XXXXXX
																XXXXX
															XXXXX
														XXXXXXXX
													BBBB
														XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
															XXXX
																XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																	XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
																		XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
																			XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																		XXXXXX
																	XXXXXX
																XXXXX
															XXXXX
														XXXXXXXX
													BBBBB					
													XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
														XXXX
															XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
																	XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
																		XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																	XXXXXX
																XXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
												XXXXX
											XXXXX
										XXXXXXXX
									XXXXXXXX
								XXXXX
							XXXXX
						XXXXXXXX
					XXXXXXXX
					XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
						XXXXXXX
							XXXX
								XXXX
									XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXX XXXXXX XXXXXX XXXXXXX X XXXXXX XXXXXXXXXXXX
										XXXXXXX
											XXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
												XXXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
														XXXX
															XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
																	XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
																		XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Total Amount') XXXXXXXXXXX
																	XXXXXX
																XXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
												XXXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
														XXXX
															XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
																	XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
																		XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																	XXXXXX
																XXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
												XXXXX
											XXXXX
										XXXXXXXX
									XXXXXXXX
								XXXXX
							XXXXX
						XXXXXXXX
					XXXXXXXX
					XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
						XXXXXXX
							XXXX
								XXXX
									XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXX XXXXXX XXXXXX XXXXXXX X XXXXXX XXXXXXXXXXXX
										XXXXXXX
											XXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXX
														XXXX
															XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
																	XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXX
																		XXXX
																			XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																		XXXXX
																	XXXXXXXX
																XXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
												XXXXX
											XXXXX
										XXXXXXXX
									XXXXXXXX
								XXXXX
							XXXXX
						XXXXXXXX
					XXXXXXXX
					XXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
						XXXXXXX
							XXXX
								XXXX
									XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XX XXXXXX XXXXX XXXXXX XXXXXX XXXXXXX X XXXXXX XXXXXXXXXXXX
										XXXXXXX
											XXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
														XXXX
															XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
																	XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
																		XX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																	XXXXXX
																XXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
												XXXXX
											XXXXX
										XXXXXXXX
									XXXXXXXX
								XXXXX
							XXXXX
						XXXXXXXX
					XXXXXXXX
					XXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
						XXXXXXX
							XXXX
								XXXX
									XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXX XXXXXX XXXXXX XXXXXXX X XXXXXX XXXXXXXXXXXX
										XXXXXXX
											XXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
														XXXX
															XXX XXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																	XX XXXXXXXXXXXXXX XXXXFFFFXXXX
																XXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
												XXXXX
											XXXXX
										XXXXXXXX
									XXXXXXXX
								XXXXX
							XXXXX
						XXXXXXXX
					XXXXXXXX
					XXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
						XXXXXXX
							XXXX
								XXXX
									XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXX XXXXXX XXXXXX XXXXXXX X XXXXXX XXXXXXXXXXXX
										XXXXXXX
											XXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXX
														XXXX
															XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																BB BBBBBBBBBBBBB BB BBBBBBB BBBBBBB BBBBB
																	XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXX XX XXXXXXXXXX XXXXXX XXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX
																BBBB
																	XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXX XX XXXXXXXXXX XXXXXX XXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX
																BBBBB	
															XXXXX
														XXXXX
													XXXXXXXX
												XXXXX
											XXXXX
										XXXXXXXX
									XXXXXXXX
								XXXXX
							XXXXX
						XXXXXXXX
					XXXXXXXX
					XXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
						XXXXXXX
							XXXX
								XXXX
									XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XX XXXXXX XXXXX XXXXXX XXXXXX XXXXXXX X XXXXXX XXXXXXXXXXXX
										XXXXXXX
											XXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
														XXXX
															XXX XXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																	BB BBBBBBBBBBBBBBB BB BBBBBBB BBBBBBBB
																		XX XXXXXXXXXXXXXX XXXXXXXX
																	BBBB
																		XX XXXXXXXXXXXXXX XXXXXXX XXX XXX XXXXXXXX XXXXX XXXXX XXXXXXXXXXX
																	BBBBB
																	
																XXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
													XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
														XXXX
															XXX XXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																	BB BBBBBBBBBBBBB BB BBBBBBB BBBBBB
																		XX XXXXXXXXXXXXXX XXXXXXXX      
																	BBBB
																		XX XXXXXXXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXX
																	BBBBB													
																XXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
												XXXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXX
														XXXX
															XXX XXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
																	XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXX
																		BBB BBB BB BBBBBBB
																			BB BBBBBBBBBB BB BBBBBBBBBBB
																				XXX XXXXXXXXXXXXXXXX XXX X XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX
																			BBBB BBBBBBBBBB BB BBBBBBBB
																				XXX XXXXXXXXXXXXXXXX XXX X XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX
																			BBBB BBBBBBBBBB BB BBBBBBBBBB
																				XXX XXXXXXXXXXXXXXXX XXX X XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX
																			BBBB BBBBBBBBBB BB BBBBBBBBBB
																				XXX XXXXXXXXXXXXXXXX XXX X XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX
																			BBBB BBBBBBBBBB BB BBBBBBBBB
																				XXX XXXXXXXXXXXXXXXX XXX X XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX
																			BBBB BBBBBBBBBB BB BBBBBBBBB
																				XXX XXXXXXXXXXXXXXXX XXX X XXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX
																			BBBBB      
																		BBBBB
																			XXXX
																				XXX XXXXXXXXXXXXXXXX XXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX
																				XXX XXXXXXXXXXXXXXXX XXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX
																				XXX XXXXXXXXXXXXXXXX XXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX
																				XXX XXXXXXXXXXXXXXXX XXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX
																			XXXXX
																		BBBBBB
									
																	XXXXXXXX
																XXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
													XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
														XXXX
															XXX XXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																	BB BBBBBBBBBBB BB BBBBBBB BBBB BBBBBBBB
																		XX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX  
																	BBBB 
																		XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																	BBBBB
																XXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
												XXXXX
											XXXXX
										XXXXXXXX
									XXXXXXXX
								XXXXX
							XXXXX
						XXXXXXXX
					XXXXXXXX
					XXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
						XXXXXXX
							XXXX
								XXXX
									XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XX XXXXXX XXXXX XXXXXX XXXXXX XXXXXXX X XXXXXX XXXXXXXXXXXX
										XXXXXXX
											XXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXX
														XXXX
															XXX XXXXXXXXXXXX
																XXX XXXXXXXXXXXXXX XX XXXXXX XXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXX XXXXXX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'All Rights Reserved.') XXXXXXXXXXXXXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
												XXXXX
											XXXXX
										XXXXXXXX
									XXXXXXXX
								XXXXX
							XXXXX
						XXXXXXXX
					XXXXXXXX
				XXXXX
			XXXXX
		XXXXXXXX
	XXXXXXXXXXXX XXX XXX
XXXXXXX

XXXXXXXXXXX
	
XXXXX