BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBB
BBBB BBBBBB
BBBB BBBB
BBBB BBBB
BBBBB BBBBBBBB
XXXX XXXXX XXXXXXXX XXXXX XXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
        BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB
        BBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBB BB BBBBBBBBB
        BBB BBBBBBBB BB BBBBBBBBB
        BB BBBBBBBBBBBBB BB BBBBBBBBBBBBBB
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
        BBBBB
        BBBBBB
    XXXXXXXX      
    XXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXBBBBBBBBBB
        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
        BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
        BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB
        BBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBB BB BBBBBBBBB
        BBB BBBBBBBB BB BBBBBBBBB
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXX 
            BB BBBBBBBBBBBBB BB BBBBBBB
                XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX
            BBBB BBBBBBBBBBBBB BB BBBB
                XXXXXBBBBBB BBBBBBBBBBBBBBBBBBX
            BBBBB  XXXXXXX XX
            XXXXXXXXX
        BBBBBB
    XXXXXXX
    XXXXXX
    XXXXXXXX
    XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


    XXXXXXXX XXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
    XXXXXXXXX
XXXX XXXXX XXXXXXXX XXX XXXXX XXX
BBBBBBBB
BBBBB BBBBBBB
    XXXX XXXXXXXBBBBB BBXXXXXXXX XXXXXXXXXXXXXXXBBBBBBBBXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXX
                                XXXXXX
                            XXXXXX
                            XXX XXXXXXXXXXX XXXXXX gettext(u'Payment Complete Successfully') XXXXX
                            XXX gettext(u'Congratulations, you have completed your purchase, we will send the receipt to your email') XXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB