>P1;cox2_parde

MMAIATKRRGVAAVMSLGVATMTAVPALAQDVLGDLPVIGKPVNGGMNFQPASSPLAHDQ
QWLDHFVLYIITAVTIFVCLLLLICIVRFNRR--ANPVPAR-------------------
--------FTHNTPIEVIWTLVPVLILVAIGAFSLPILFRSQEMPNDPDLVIKAIGHQWY
WSYEYPNDG------------------------------------------------VAF
DALMLEKEALADAGYSEDEYLLATDNPVVVPVGKKVLVQVTATDVIHAWTIPAFAVKQDA
VPGRIAQLWFSVDQEGVYFGQCSELCGINHAYMPIVVKAVSQEKYEAWLAGAKEEFAADA
SDYLPASPVKLASAE
*

>P1;cox2_acaca

-----------------------------------LCLNDHTNSWKIGFQDPTTPIAYGI
IKLHDHILFFLAVILFVVGYLLLSTYKKFYYGSLNNDLPESKRISLFDTLINTYKENLSF
NVTNRTYNINHGTTIEIIWTILPAFILLFIAVPSFALLYAMDEII-DPVLTVKVIGHQWY
WSYEYSDYSVVYSNRMLDYDSIDRFAAMEMMYKGMGYLKDRSLLSYLYIPMVIPETTIKF
DSYMIHEAELNLGDLR----LLKTDMPLFLPKNTHIRLLITSSDVLHSWAVPSFGVKVDA
VPGRLNQTSLYLKNTGTFYGQCSELCGVNHAFMPIEVYVVNPVYFYNYVYIYFKNFNLI-
---------------
*

>P1;cox2_allma

-------------------------MKLLN-----FIYNDHPQPWQIGFQDGATTTFYGI
VDLHDNIIFYLIIVIIGVTWIQTSVMLDSYGN--SDKHVYK-------------------
-------YSHHGTLVEIIWTITPALILVAIAFPSFKLLYLMDSVV-DPAVTVKAIGYQWY
WGYNYGDYN----------------------------------------------EDISF
DSFMVPTDELEMGQFR----LLEVDNRVVVPVDTRVRIVVTAADVIHSFAVPSLGIKIDA
IPGRINQASFLIDREGVYYGQCSELCGANHGFMPIAIEAVSLDRYVAWVDAQLS------
---------------
*

>P1;cox2_apec

----------------------------------------MANWTQLGLQDASSPLMEEL
IYFHDYTLIILTLITILVFYGLASLLFS--------SNTN--------------------
------RFFLEGQGLETVWTIIPAVILIFIALPSLQLLYLMDEVN-NPYLTIKAIGHQWY
WSYEYADYR-----------------------------------------------ELEF
DSYMIPTSDLTSGNPR----LLEVDNRLTLPAQTPIRVLVSSADVLHSWAIPSLGIKMDA
VPGRLNQVNFFISRCGLFYGQCSEICGANHSFMPIVIESVNFSTFETWVSNFITE-----
---------------
*

>P1;cox2_arath

--------------------MIVLKWLFLT-----ISPCDAAEPWQLGSQDAATPIMQGI
IDLHHDIFFFLILILVFVLWILVRALWHFHYK--KNAIPQR-------------------
--------IVHGTTIEILRTIFPSIISMFIAIPSFALLYSMDEVVVDPAITIKAIGHQWY
RTYEYSDYNSS------------------------------------------DEQSLTF
DSYMIPEEDLELGQSR----LLEVDNRVVVPAKTHLRIIVTSADVPHSWAVPSSGVKCDA
VPGRLNQISILVQREGVYYGQCSEICGTNHAFTSIVVEAVPRKDYGSRVSNQLIPQTGEA
---------------
*

>P1;cox2_balca

----------------------------------------MATWAQLGFQDAASPIMEEL
IYFHDHALVILTLVTIIVFYGLISLITN--------SFTN--------------------
------RFLLEGQEIETIWTIIPAIILIFLALPSLRLLYLMDEIN-DPHLTIKAIGHQWY
WSYEYTDYQ-----------------------------------------------DLEF
DSYMVPTQDLTPGQPR----LLEVDNRLVAPTHSPVRVLVTSADVLHSWAIPALGLKMDA
VPGRLNQLTFFAPRSGVFYGQCSEICGANHSFMPIVLESVPLPYFENWVSSLVE------
---------------
*

>P1;cox2_chocr

--------------------MNNILNFYPA-----VITTDVAENWQIGFQDPATPIMEGI
INLHYDLMFFICVISVFVSWMLGRTLWHFEQN--QNKIPSS-------------------
--------LTHGTLIEMIWTVTPAFILLIIAVPSFSLLYAMDEII-SPAITIKTLGHQWY
WSYEYSDYLNE------------------------------------------DDDSINY
DSYMIPEEDLEIGQFR----LLEVDNRMVIPINTHIRVIVTAADVLHSWAVPSFRSKCDA
IPGRLNQTSLFIKREGVYYGQCSEICGINHGFMPIVVEATSLPNYVSWISNKLNE-----
---------------
*

>P1;cox2_drome

----------------------------------------MSTWANLGLQDSASPLMEQL
IFFHDHALLILVMITVLVGYLMFMLFFN--------NYVN--------------------
------RFLLHGQLIEMIWTILPAIILLFIALPSLRLLYLLDEIN-EPSVTLKSIGHQWY
WSYEYSDFN-----------------------------------------------NIEF
DSYMIPTNELMTDGFR----LLDVDNRVVLPMNSQIRILVTAADVIHSWTVPALGVKVDG
TPGRLNQTNFFINRPGLFYGQCSEICGANHSFMPIVIESVPVNYFIKWISSNNS------
---------------
*

>P1;cox2_human

----------------------------------------MAHAAQVGLQDATSPIMEEL
ITFHDHALMIIFLICFLVLYALFLTLTT--------KLTN--------------------
------TNISDAQEMETVWTILPAIILVLIALPSLRILYMTDEVN-DPSLTIKSIGHQWY
WTYEYTDYG-----------------------------------------------GLIF
NSYMLPPLFLEPGDLR----LLDVDNRVVLPIEAPIRMMITSQDVLHSWAVPTLGLKTDA
IPGRLNQTTFTATRPGVYYGQCSEICGANHSFMPIVLELIPLKIFEMGPVFTL-------
---------------
*

>P1;cox2_ktun

----------------------------------------MAFWSQWGFQDGASPIMEQL
IFFHDHAMLILIMIISLLSYGAVSLMNN--------SFLS--------------------
------RSTLESQEIEIVWTILPAVVLIFLAFPSLQLLYLLDELE-EPALTIKVVGHQWY
WSYEYSDFL-----------------------------------------------NLEF
DSYMISLEDLEEGDYR----LLEVDHRSVVPMKTKVRVLVTAADVLHSWTVPSLGVKADA
VPGRLNQLSFFANYPGVFYGQCSEICGANHSFMPIVLEVVDSSSFIKWIMFNGEA-----
---------------
*

>P1;cox2_lter

----------------------------------------MPNWGQVMFQDAASSVMLQL
VSFHDHALLVLTLVLTVVGYALLALMLN--------KQVN--------------------
------RYIMEAQTVETIWTILPALILLVLALPSLRILYITDEVS-QPSITVKTIGHQWY
WSYEYTDFL-----------------------------------------------NVEM
DSYMLPTSDLLPGDYR----LLEVDNRMVVPMQLEIRMLITAADVIHSWTVPALGVKVDA
VPGRLNQIGFTTTQPGVFYGQCSEICGANHSFMPIAVEAINTKSFMSWVSNFKP------
---------------
*

>P1;cox2_marpo

---------------------MNLIWIFP------IAFCDAAEPWQLGFQDPATPMMQGI
IDLHNDIFFFLIVILIFVLWMLVRALWHFHYK--RNPIPER-------------------
--------IVHGTTIEIIWTIFPSIILMFIAIPSFALLYSMDEVV-DPAITIKAIGHQWY
WTYEYSDYNSS------------------------------------------DEQSLTF
DSYMIPEDDLELGQLR----LLEVDNRVVVPAKTHLRMIITSADVLHSWAVPSLGVKCDA
VPGRLNQTSIFIKREGVYYGQCSELCGTNHGFMPIVVEAVSLDDYVSWVSNKLD------
---------------
*

>P1;cox2_metse

-----------------------MTNLLNNWLIINQFGYDLPEPWQLGLQDAAHPVMEEI
IFFHDQVMFILIIIITTVLWLIVKALSG--------KAYH--------------------
------RYLVDGTLLEIIWTIVPAIILILIAFPSLKLLYLMDEVM-DPALTIKAIGHQWY
WSYEYSDYQTE---------------------------------------------TLEF
DSYMVPTSELNKGDFR----LLEVDNRLVVPINTHVRVLVTGADVLHSFAVPALAVKMDA
IPGRLNQTGFFIKRPGIFYGQCSEICGANHSFMPIVIEAVSLDKYINWVLSGSDE-----
---------------
*

>P1;cox2_picca

-----------------------MLLIMNN-----MMNNDVPTPWGVYFQDSATPNHEGI
MELHDNIMFYLVLILCLVSWLLFSMVKD--GS--KNPLPHK-------------------
-------YLVHGQTIEIIWTILPALVLLVMAFPSFMLLYLCDEVI-SPAMTIKAIGTQWY
WKYEYSDFIND------------------------------------------SGETIEF
ESYVIPEDTLEDGQLP----LLDTDTSIVCPVNTHIRFIVSAADVIHDFAVPSLGIKIDA
CPGRLNQVSALIQREGVYYGQCSETCGVAHSAMPIKVEAVSLKEFLTWLNEQ--------
---------------
*

>P1;cox2_podan

----------------------MFFLINKL-----VMNFDAPSPWGIYFQDSATPQMEGL
NELHDNIMYYLVVILFAVGWILLSIVINYVST--KSPISHK-------------------
-------YLNHGTLIELIWTITPAVILILIAFPSFKLLYLMDEVS-DPSMSVLAEGHQWY
WSYQYPDFLDS------------------------------------------NDQFIEF
DSYIVPESDLDEGGLR----MLEVDNRVVLPELTHVRFIITAGDVIHSFAAPALGIKCDA
YPGRLNQVSVFINREGVFYGQCSEICGILHSSMPIVIESVSLEKFLIWLKEQ--------
---------------
*

>P1;cox2_prowi

-----------------MKFLLFAYALIPF-----VSFSDAPEAWQIGFQDPATPIMQGL
IDLHHDIQFFLIAVLVFVVWMVSRALYLFHYT--RNPLPEK-------------------
--------IIHGTLIEIVWTITPSLILIFIAVPSFALLYSLDEVV-DPAVTIKAIGHQWY
WSYEYSDYSIA------------------------------------------DDQSIAF
DSYMIPDDDLELGQYR----LLEVDNRVVVPVDTHIRVIITAADVLHSWAIPSLGVKCDA
VPGRLNQIPMFIKREGVFYGQCSELCGTNHAFMPIVVEAVSLENYISWVSNKLEEL----
---------------
*

>P1;cox2_recam

------------------MFLVALIFIIISYGMVDSLRADYAEKWQLDFQDPATPVMEGI
INLHHDLWFFLILIAVFVLWILLRTLWFFDRS--RGTVPSK-------------------
--------VVHGTVLEIVWTIAPSFILLAIAIPSFALLYSMEEST-DPAITLKAIGHQWY
WSYEYSDYTT-------------------------------------------DSESLAF
DSYMLPESELKEGQLR----LLEVDNRIFLPTHTHLRVLITSSDVLHSWAVPSLGVKVDA
CPGRLNQASIFLKREGIFYGQCSEICGVNHGFMPIVIEAVPLKEYVSWVSSQIQI-----
---------------
*
