>P1;cytb_parde

MAGIPHDHYEPKTGFERWLHRRLPIVSLVYDTLM-IPTPKNLNWWWIWGIVLAFCLVLQI
ATGIVLVMHYTPHVDLAFASVEHIMRDVNGGYMLRYLHANGASLFFLAVYIHIFRGLYYG
SYKAPREVTWIVGMLIYLMMMGTAFMGYVLPWGQMSFWGATVITGLFGAIPGVGEAIQTW
LLGGPAVDNPTLNRFFSLHYLLPFVIAALVVVHIWAFHTTG-NNNPTGVEVRRGSKEEAK
KDTLPFWPYFVIKDLFALAVVLVVFFAIVGFMPNYLGHPDNYIEANPLVTPAHIVPEWYF
LPFYAILRAFTADVWVVMLVNWLSFGIIDAKFFGVIAMFGAILVMALVPWLDTSRVRSGQ
YRPLFKWWFWLLAVDFVVLMWVGAMPAEGIYPYIALAGSAYWFAYFLIILPLLGIIEKPD
AMPQTIEEDFNAHYGPETHPAE---
*

>P1;cytb_acaca

----------------MRFIKKYPLLNIVNSFLIDYPAPPNISYLWNFGALAAFCLGIQI
VTGIFLAMFYVPSIESAFSSVQYIMRDVNYGWLIRYIHANGASFFFICVYIHVFRGLYYN
SYITPRELLWNLGVTILIVMILTAFLGYVLPWGQMSFWAATVITSLFSAIPVVGEYIVIW
LWGGFSVDNATLNRFFSLHYLLPFVIALLSLIHVAVLHESG-SSNPLNIALS-------V
ANKVPFHPYFIFKDLLGIIFFLIVFCYAVFFKPDSIIDPINNVPANPLVTPTHIVPEWYF
LPFYAILRS------------------IPNKLGGVITLGLALIVLFLLPFITNNVFKGSF
FEISKTILFWSFFSVCVLLGWIGFKPIEDPYLMLGQMLTVLYFFYFFSLAVIVPTLQAYT
FKNVFAK------------------
*

>P1;cytb_allma

----------------MRFLKSHPVLSLANSFLIDSPLPSNITYLWNFGSLLGLCLVIQI
VTGVTLAMHYAPSTSLAFVSVEHIMRDVFYGWLIRYAHANGASFFFICVYIHMARGLYFN
SYTKPRVLLWSVGVVIYILMMATAFLGYVLPWGQMSFWGATVITNLLSAIPYIGTALVEF
VWGGFSVDNATLNRFFSLHYLLPFILAALVVVHLIALHEHG-SNNPLGISS--------K
VDRLPFHPYFTYKDLVGFFVFFLIFFGFVFYQPNLMGHPDNYIPANPLVTPVSIVPEWYF
LPFYAILRA------------------IPSKLGGVIGMFGALLILLALPWLETSKVRGAG
FRPVMKFFFWLFVVNFFLLMYCGGQHAEEPFITLSRICTAYYFMYFLVIIPVIGHLENLL
HRCRD--------------------
*

>P1;cytb_apec

-------------IMTGPLRKNHPLFSIINNSLIDLPSPSNLSIWWNFGSLLGLCLIIQI
LTGLFLAMHYTSDVSLAFSSVSHICRDVNYGWLLRNIHANTASFFFLCLYFHIGRGIYYG
SYVNNE--TWNIGVILLLLTMLTAFVGYVLPWGQMSFWGATVITNLISAVPYIGSSIVQW
VWGGFSVDNATLTRFFAFHFLFPFIIAALSIIHLFFLHQTG-SNNPTGIES--------K
FDKTPFHTYFSTKDITGFIILFMLLSSIVLLSPNLLNDPENFNPANPLVTPIHIQPEWYF
LFAYAILRS------------------IPNKLGGVVALLASILVLFLVPFLHTSNNQANT
FRPASQSLFWLLTSVFIILTWLGSQPVEDPFILLGQISSIAYFALFFLAFPLASELENKL
IF-----------------------
*

>P1;cytb_arath

----------MTIRNQRFSLLKQPISSTLNQHLVDYPTPSNLSYWWGFGPLAGICLVIQI
VTGVFLAMHYTPHVDLAFNSVEHIMRDVEGGWLLRYMHANGASMFLIVVYLHIFRGLYHA
SYSSPREFVWCLGVVIFLLMIVTAFIGYVLPWGQMSFWGATVITSLASAIPVVGDTIVTW
LWGGFSVDNATLNRFFSLHHLLPFILVGASLLHLAALHQYG-SNNPLGVHS--------E
MDKIAFYPYFYVKDLVGWVAFAIFFSIWIFYAPNVLGHPDNYIPANPMSTPPHIVPEWYF
LPIHAILRS------------------IPDKAGGVAAIAPVFICLLALPFFKSMYVRSSS
FRPIHQGMFWLLLADCLLLGWIGCQPVEAPFVTIGQISPLVFFLFF-AITPILGR-VGRG
IPNSYTDETDHT-------------
*

>P1;cytb_balca

--------------MTGPIRKNHPLISIANGALVDLPSPSNLSAWWNFGSLLGLCLITQI
LTGLFLAMHYTADISLAFSSVAHICRDVNYGWLLRNIHANGASFFFICIYLHIGRGLYYG
SYVNQE--TWNIGVLLLLATMATAFFGYVLPWGQMSFWGATVITNLFSAIPYVGPDIVQW
LWGGFSVSNATLTRFFTFHFVLPFIIAALSMLHLLFLHQTG-SNNPTGLNS--------N
IDKVVFHTYFSYKDVFGFIALLFGLLFIALFLPTALGDPENFVPANPLVTPVHIQPEWYF
LFAYAILRS------------------IPNKLGGVIALFASIVILFAVPILHSAHHQTIA
FRPLAQVVFWALIADTLLLTWIGGQPVEDPYIILGQLSSAIYFLCFLVLIPTAGILENRL
NLNPL--------------------
*

>P1;cytb_chocr

-----------------MRFIKRPLISIVNDHLIDYPTPINIHYAWNFGFLSSICLIVQI
LTGIFLAMHYTPHVDLAFASVEHIMRDVNYGWLLRYIHTNGASMFFIVVYIHIFRGLYFG
SYIKPRHWVWVIGVLILLLMILTAFIGYVLPWGQMSLWGATVITNLVSAVPFIGDSIVTW
LWGGFSVDNATLNRFFSLHYLMPFVIAAVSLVHLAILHQDG-SGNPLGIDS--------N
VDKVSMFPYFIVKDFLGMVIFIIFFSIFVYFSPNVLGHPDNYIEANPMVTPAHIVPEWYF
LPFYAILRS------------------IPHKLGGVTAMISAIAILAFLPWIHSTEIRSSR
FRPLYRLFYWVMISCCLILGWIGGMPVENPYVIIGQIASIYYFIYFIILLPVLGRIEKFL
LEFKI--------------------
*

>P1;cytb_drome

--------------MNKPLRNSHPLFKIANNALVDLPAPINISSWWNFGSLLGLCLIIQI
LTGLFLAMHYTADINLAFYSVNHICRDVNYGWLLRTLHANGASFFFICIYLHVGRGIYYG
SYKFTP--TWLIGVIILFLVMGTAFMGYVLPWGQMSFWVATVITNLLYAIPYLGMDLVQW
LWGGFAVDNATLTRFFTFHFILPFIVLAMTMIHLLFLHQTG-SNNPIGLNS--------N
IDKIPFHPYFTFKDIVGFIVMIFILISLVLISPNLLGDPDNFIPATPLVTPAHIQPEWYF
LFAYAILRS------------------IPNKLGGVIALVLSIAILMILPFYNLSKFRGIQ
FYPINQVMFWSMLVTVILLTWIGARPVEEPYVLIGQILTVVYFLYYLVNPLITKWWDNLL
N------------------------
*

>P1;cytb_human

--------------MT-PMRKINPLMKLINHSFIDLPTPSNISAWWNFGSLLGACLILQI
TTGLFLAMHYSPDASTAFSSIAHITRDVNYGWIIRYLHANGASMFFICLFLHIGRGLYYG
SFLYSE--TWNIGIILLLATMATAFMGYVLPWGQMSFWGATVITNLLSAIPYIGTDLVQW
IWGGYSVDSPTLTRFFTFHFILPFIIAALATLHLLFLHETG-SNNPLGITS--------H
SDKITFHPYYTIKDALGLLLFLLSLMTLTLFSPDLLGDPDNYTLANPLNTPPHIKPEWYF
LFAYTILRS------------------VPNKLGGVLALLLSILILAMIPILHMSKQQSMM
FRPLSQSLYWLLAADLLILTWIGGQPVSYPFTIIGQVASVLYFTTILILMPTISLIENKM
LKWA---------------------
*

>P1;cytb_ktun

--------------MLKPIRSSHPVFKIINGSLIDLPSPSNLSIWWNFGSLLGLCLIIQI
LTGLFLAMHYATNIELAFSSVAHICRDVNYGWLIRAAHANGGSLFFICLYFHIGRGMYYG
SFVNIH--TWXVGVILLFLTMGTAFIGYVLPWGQMSFWGATVITNLMSAIPYIGTTMVQW
IWGGFAVDNATLTRFFSFHYLAPFIIAAASVLHILFLHETG-SNNPLGINS--------D
SEKVTIHSFYTLKDLVGFVVMVIFLLLLVFLDPNLLAHPDNFIPANPLVTPTHIQPEWYF
LFAYAILRS------------------IPNKLGGVVGLLMSIVILFFVPLINLGKFRTIS
FYPVTQILYWSLVSVFLLLTWIGAQPVEDPFILIGQILTFVYFLLFLMIPLTKKMWDWTI
NF-----------------------
*

>P1;cytb_lter

--------------MFKPIRTTHPAIKIINSTLIDLPAPNNISIWWNYGSLLGLCLVIQV
LTGLFLSMHYVPNIEMAFSSVALISRDVNYGWLLRSIHANGASMFFLFIYLHAGRGLYYG
SYNLSE--TWNIGVILFLLTMATAFMGYVLPWGQMSFWGATVITNLFSAIPYIGKTLVEW
IWGGFAVDNATLNRFFAFHFILPFAIMGATILHIMFLHESG-SNNPIGLNA--------D
SDRIPFHPYYSIKDTLGYTLAISALSLMVLFEPNLFTDPENFLMANPLVTPIHIKPEWYF
LWMYAILRS------------------IPNKLGGVMALFAAIVILFIPPLTSVMNKRSLS
FYPLNKTMFWGLVASWAILTWIGGRPVEDPFIIIGQVFTSLYFIYFISSPTISKLWDDSI
II-----------------------
*

>P1;cytb_marpo

-----------MAR--RLSILKQPIFSTFNNHLIDYPTPSNISYWWGFGSLAGLCLVIQI
LTGVFLAMHYTPHVDLAFLSVEHIMRDVKGGWLLRYMHANGASMFFIVVYLHFFRGLYYG
SYASPRELVWCLGVVILLLMIVTAFIGYVLPWGQMSFWGATVITSLASAIPVVGDTIVTW
LWGGFSVDNATLNRFFSLHYLLPFIIAGASILHLAALHQYG-SNNPLGINS--------S
VDKIAFYPYIYVKDLVGWVAFAIFFSIFVFYAPNVLGHPDNYIPANPMSTPAHIVPEWYF
LPVYAILRS------------------IPNKLGGVAAIGLVFVSLLALPFINTSYVRSSS
FRPIHQKFFWLLVADCLLLGWIGCQPVEAPYVTIGQIASVGFFFYF-AITPILGKCEARL
IKNSNACEARSVLASFLTSIGLLWW
*

>P1;cytb_metse

----MVGYAMGHSRPTMQFRKENPVLSIVNGIIIDLPAPANLSYMWNFGSLLGVCLVVQM
ATGIFLAMHYCSDVSLAFASVDHIMRDVNYGFLLRYFHANGASMFFLCLYFHVGRGIYYG
SYTKVE--VWNVGVVLFILTMATAFLGYVLPWGQMSFWGATVITNLLSAIPYVGTDIVQW
VWGGFSVSNATLNRFFSLHYLLPFVLAALGVVHLICLHVSG-SNNPIGVRS--------D
LDKVPFHTYYTSKDWYGIVAFVLFFCSLVYLAPNLLGDPENFIQANPLVTPVHIQPEWYF
LFAYAILRS------------------IPNKLGGVVAMFASLLILFLLPWVHTSRLRGLT
FRPLARVAFWFMVTDFMLLTWIGCQPVEEPFIIVGQLASVFFFAYFLVLSPLLGYLENLL
LFPKKG-------------------
*

>P1;cytb_picca

----------------MAMRKSQVYTSLANSYLMDSPQPSTLNYWYNLGSLLGLCLVMQM
ASGMFLAMHYSSHMDLAFASVEHMMRDVNYGYLMRYMHANGASFFFVCMYAHMGKAMYYG
SYKSPRVLVWVMGVVMFIMTMATAFLGYCWVYGQMSHWGATVITNLFSAIPFIGKDLVPF
IWGSFSVSNPTMQRFFALHYLCPFMLAALVMMHLMALHVHG-SSNPLGMSS--------N
MDRLPFHGYFVFKDLVTVFVFLLMFSLFVFFSPNTLGHPDNYMPGNPLVTPASIVPEWYL
LPFYAILRS------------------IPDKLGGVMAMFAAMLMLLVLPVTDRSVVRGNT
FKIMSKTFFFLFTYNFILLGQLGQLHVEVPFIQLGQFATLNYFTYFMFIVPVVSTLENIL
FYIGRVHNN----------------
*

>P1;cytb_podan

----------------MRILKSHPLLKLVNSYLIDASQPSNISYLWNFGSLLLLCLIIQI
ITGVTLAMHYSPNVLEAFNSIEHIMRDVNNGWLVRYLHSNTASAFFFLVYLHIGRGMYYG
SYRAPRTLVWAIGTVILIVMIVTAFLGYVLPYGQMSLWGATVITNLVSAIPWIGQDIVEF
IWGGFSVNNATLNRFFALHYLLPFILVALVLMHLIALHDTAGSSNPLGISG--------N
YDRITFAPYYLFKDLITIFIFIFVLSSFVFFMSNVLGDSENYIMANPMQTPAAIVPEWYL
LPFYAILRS------------------IPNKLLGVIAMFAAILAIMLLPITDLGRSKGLQ
FRPLSKFAFWVFVVNFLILMKLGACHVETPFIELGQLSTALYFGHFIIIVPIISLIENTL
VDLNTMSKG----------------
*

>P1;cytb_prowi

--------------MKRLSIIKQPILSILNDHIVDYPSPSNINYFWSLGSIAGICLVVQI
ATGIFLAMHYTPHIDLAFMSVEHIMRDVEGGWLLRYMHANGASMFFIVVYIHMFRGLYYG
SYTSPRELLWIVGVAILLLMIITAFIGYVLPWGQMSFWGATVITSLASAIPVVGNSIVTW
LWGGFSVDNATLNRFFSLHYLLPFVLVGLSVVHLAALHQYG-SNNPLGTSS--------A
VDKLALYPYFYVKDLVGWVGFAIFFSVFVYFFPNLLGHPDNYIPANPMSTPAHIVPEWYF
LWVYAILRS------------------IPNKLAGVGAIALVFISLFSLPFLNTSPIRSNN
FKPIHRKFFWLILADCFLLSWIGQQPVEDPYIIIGQLASVFFFFYFLVVVPLTGKLEHYL
IKYKS--------------------
*

>P1;cytb_recam

-----------------MRLLKRPLIRELNSFIVDYPTPSNLSYWWNFGFIAAFCLVVQI
ATGIFLAMHYTPHVDLAFISVEHIMRDVNYGWLMRYIHANGASMFFIAVYIHMFRGLYYG
SYASPREFLWIIGVIILLIMILTAFMGYVLPWGQMSFWGATVITNLASAVPYIGEHIVYW
LWGGFSVDNATLNRFYSLHYLFPFIIAGLVGLHLIVLHEDG-SNNPLGIDS--------K
VDKIPFYPYYYVKDLFGIVVFGLFFSVFVFFYPNLLGHPDNYIEANPLVTPPHIVPEWYF
LPFYAILRS------------------IPNKLLGVIAMLVSILILIALPFLNTSEIRSSQ
FRPIHRKLFWLFFVDCVILGWIGGNVPETPYLEIGQIATVFYFAYFLVFIPLLGKLESYL
INLDTNQYQKHLVK-----------
*
