>P1;nad5_parde

-------------MEKFVLFAPLIASLIAGLGWRAIGEKA--------------------
--------------AQYLTTGVLFLSCLISWYLFLS----FDGVPRHIPVLDWVVTGD--
FHAEWAIRLDRLTAIMLIVVTTVSALVHMYSLGYMAHDDNWTHDEHYKARFFAYLSFFTF
AMLMLVTADNLLQMFFGWEGVGVASYLLIGFYYKKASANAAAMKAFIVNRVGDFGFLLGI
FGIYWLTGSVQFDEIFRQVPQLAQT--EIDFLWRDWNAANLLGFLLFVGAMGKSAQLLLH
TWLPDAMEGPTPVSALIHAATMVTAGVFLVCRMSPLYEFAPDAKNFIVIIGATTAFFAAT
VGLVQNDIKRVIAYSTCSQLGYMFVAAGVGVYSAAMFHLLTHAFFKAMLFLGAGSVIHAM
HHE-QDMRNYG--GLRKKIPLTFWAMMIGTFAITGVGIPLTHLGFAGFLSKDAIIESA--
---YAGSG----YAFWLLVIAACFTSFYSWRLIFLTFYGKPRGDHH--------------
-AHDHAHESPPVMTIPLGVLAIGAVFAGMVWYGPFFGDHHKVTEYFHIAGAHHEAAEGEE
AEHATAEAPVEHAVADTATAEGEAAAEAEHAEIAAPVGGAIYMHPDNHIMDEAHHA--PA
WVKVSPFVAMVLGLITAWTFYIANPS--LPRRLAAHEP--ALYRFLLNK-WYFDEIYEFI
FVRPAKWLG-RVLWKGGDGAVIDGTINGVAMGLIPRLT-RAAVRVQSGYLFHYAFAMVLG
----IVGLLIWVMMRGAH-----------------------------
*

>P1;nad5_acaca

-------------MYLLPLLFPLLNLFISCILGKFLGKR---------------------
--------------VLFVLVINMLFSAIFSFWIFYEVG--INKSVCYIDLGPWFHIGL--
LKLNWLFLFDSITSVMLVLVVFVSLLVHLYSIDYMSGDP-------HIIRFLGYLSLFTF
FMLMLVTSGNFVQLFLGWEGVGLSSYLLINFWYTRIQANKSAMKAIIVNRFGDFGIYFSL
LVIFFFFKSFDFGVVFNLVQFLDTQP-RMSFLGFSLNRVDLIVIFLFLGAIGKSAQLGLH
TWLPDAMEGPTPVSALIHAATMVTAGVFVLIRSSPILEYSSTGLFLVSLIGGLTALFAGT
VGLVQYDIKKVIAYSTCSQLGYMFFACGMSNYSVGLFHLFNHGFFKALLFLGAGSVIHAL
LDE-QDMRKMG--GLIKLMPLTYVAILVGSLSLTGFPF------LTGFYSKEVVLEI---
-AFSKFSIN-SFFIYWLGVFAAFITSFYSIRLMYLVFFARPNSHAR--------------
-AVNSSHESSSFIFYVLAFLGFLSIFIGFIFKDLFIG-------------------LG--
---------------------------------TDFWANSIFNLYVNSDILYAEFL--DY
YYKLIPLVFSIVGLFFSLFVYFVIYDYTVFVVKNKFFR--YAYFFLAKK-WYFDLLYNNI
FVFNLLSSFYLLTFKIIDRGLIELFGPLSFVRLINKSS-IIFSSFQTGFLYNYIFVVLLG
LMFFIKLTSSLFFPSFNSFFNFGLFICLLSLIIFLSFGNKKQNI---
*

>P1;nad5_allma

-------------MYLTIITLPLFAFLTVGVIGRKLGVRG--------------------
--------------SQIITSLSIIISAILSLYGFYEIVLLNNLGPITIYLSPWMNVIG--
AHADWAFYFDSISITMCVVVSSISSLVHLYSIGYMQGDP-------HIQRFFSYLSLFTF
FMLLLVTGNNYLLMFVGWEGIGVSSYLLINFWFTRIQANKASMQAMLVNRVGDLGFVLGL
FGIFWLFGSSDYDTVGIIAYK------------LDEQYITIVTLFLLIAAIGKSAQLGLH
TWLPSAMEGPTPVSALIHAATLVTAGVYLILRSSPLFELAPTSLICVCVIGSLTAIFAAT
TGLFQNDLKRVIAYSTCSQLGYMVFALGLSQYEVAFFHLFNHAYFKALLFLSAGSIIHAL
HDE-QDMRKMG--GLVNILPFTYTMILIGSLSLMALPF------LTGYYSKDAILEVA--
YGQFLVTGT---FTYWLGTITATITAFYSSKALILGFFGTPNGSKK--------------
-IYNTIHEAPLIMSIPLFLLSICSIFIGYITNKHLSVIG-----------------IG--
---S-----------------------------SGIISGGVGTLRDHYLGFDIEFISTSF
GVQFYPLFASLLGISLALIVLKDPKKMHSIEKPEGLLNTVNITRWLSSKSYWFDNVYNTV
LISGSLHFG-GIFARDIDKGFLSLLGPQGLQQLLITISRFFAIKIDTGFIPHYASIIIII
P---IFIILSIFI----------------------------------
*

>P1;nad5_apec

-----------VNINPSIIILTINISIIITLLSSVFFFQN----ETNPSNLNSSSYSLG-
--IFHNTSFNYLFSNSLFFTSLLKTLAILSLFPLFIEII-FNIPDTTVSLFNWLPNNG--
FSLNVEFRFDLKFNTFLSVALIVSWSILEFSYYYMDNDP-------NPNNFFRLLIIFLL
NMIILTSTNNIFLLFIGWEGVGFLSFLLISWWTSRANANNSAIQAVIYNRVGDIGILLFF
SLSITLFNTWSLPEIFSISAP--------------NTFNNLLLVGLLIAAAGKSAQFGLH
PWLPAAMEGPTPVFSIRHSSTMVVAGIFLLIRLSPLYACSSNFNTWCLILGSITAIFAAT
TAISQHDIKKIVAYSTTSQLGLMMVAIGLNQPSIALFHICTHAFFKAMLFLSSGSIIHSL
NDE-QDIRKMG--GLHFILPNTAACIILGSLALSGIPF------LPGFYSKDLILEIG--
-L-TNFSN---FMGIVLSLLATLLTSVYSFRIIFFCFIKNPSFS----------------
-PLAPINEENNNLTNSLNRLALGTILSGWILTNLTVL-----------------------
-------------------------------------VPIITIS---------------S
VLKTAALLLTITGVLFSI---SILQELTLNISPPTAYN---TNSFTTNQ-WFYENISHIL
FLFYSFTISLSLSTRNIDRGWSENIGAQGIAITSSNAS-QSYQLSQTGYIKQYLLFSFLT
----LLIIIALSLTTISQLSPSFDI----------------------
*

>P1;nad5_arath

-------------MYLLIVFLPLLGSSVAGFFGRFLGSEG--------------------
--------------SAIMTTTCVSFSSILSLIAFYEVA--PGASACYLRIAPWISSEM--
FDASWGFLFDSPTVVMLIVVTSISSLVHLYSISYMSEDP-------HSPRFMCYLSILTF
FMPMLVTGDNSLQLFLGWEGVGLASYLLIHFWFTRLQADKAATKAMLVNRVGDFGLALGI
SGRFTLFQTVDFSTIFARASA---PRNSWISCNMRLNAISLICILLLIGAVGKSAQIGSH
TWSPDAMEGPTPVSASIHAATMVTAGVFMIARCSPLFEYPPTALIVITSAGATTSFLAAT
TGILQNDLKRVIAYSTCSQLGYMIFACGISNYSVSVFHLMNHAFFKALLFLSAGSVIHAM
SDE-QDMRKMG--GLASSFPLTYAMMLIGSLSLIGFPF------LTGFYSKDVILELA--
YTKYTISGN---FAFWLGSVSVLFTSYYSFRLLFLTFLVPTNSFGR--------------
-DISRCHDAPIPMAIPLILLALGSLFVGYLAKDMMIG-------------------LG--
---------------------------------TNFWANSPLVLPKNEILAESEFAA-PT
ITKLIPILFSTSGAFVAYNVNPVADQFQRAFQTSTFCN--RLYSFFNKR-WFFDQVLNDF
LVRSFLRFGYEVSFEALDKGAIEILGPYGISYTFRRLA-ERISQLQSGFVYHYAFAMLLG
--STLFVTFSRMWDSLSSWVDNRSSFILIVSSFYTKSSQE-------
*

>P1;nad5_balca

-----------MTLPLSTIISSCFSTVLILLVLAILSPSSSRVLPLQAPQLGHTSPLIGA
QLKFTNRFLSIIHQTSPTTTSLVKWSFIVSLIPSLIILP-THLSASALEWT-WLSIDS--
FSLHINFRYDIYSILFTSVALYITWSILEFSQYYMSSDP-------NVNTFSRLLTIFLM
AMILLISANNLFQLLIGWEGVGFLSFLLIGWWFTRAEANTAALQAIIYNRAGDIGILLAA
GYMIISHSTWTIDALFSHPNPS-------------HLLVNPFLWGCLIAAVGKSAQFGLH
PWLPAAMEGPTPVSALLHSSTMVVAGVFLLIRVSPLLPYSGTFQQATLIIGSLTALFAAS
CAILQHDIKKIVAFSTTSQLGLMAYAVGLNLPLLAFFHICTHGFFKAMLFLCSGSTIHDT
SNE-QDLRKMG--GLAHAVPTTAACLSLGSLALFGTPF------LAGFYSKDLILESA--
-S-ASFTG---LITLGFAMLATALTAVYSARIITSTFSQAGTLN----------------
-PINPISEELNSLTNPLKRLAAGTTIAGWALLPLLLP-----------------------
-------------------------------------AHSISPTP--------------L
WLKTAALTVTLIGLITAANLSTVINSPTAQAHTSLLGS---IRSFLTSF-WHFPETIHLL
QSNSWLSTGQTLTTRIFDRGWGEQVGAQGLGSINSLMS-TQIQATQSGLIKQYIAVAILS
----LLLIALIALTLN-------------------------------
*

>P1;nad5_chocr

-------------MYLLILFLPLLGSLISGFGGRWLGCRG--------------------
--------------TNTFSTLCVVVSSLFSLLAFFEIG--LTNTTCTIFLVSWIKSGA--
FYVSWGFLFDSLTVTMLVVITLVSSLVHIYSIKYMENDP-------HQPRFMSYLEIFTF
FMLILVTADNLIQMFLGWEGVGLASYLLINFWYTRLAANQSAIKALIVNRVGDFGLSLGI
FLIFWVFNSVDYSVIFSLVPLFDNQ--FLTFLGFKLHVLTLISLFLFIGAIGKSAQLGLH
TWLPDAMEGPTPVSALIHAATMVTAGVFLMIRFSPLLEFSPTILFILITFGSLTAFFAAV
TGVFQHDLKRVIAYSTCSQLGYMIFSCGMSCYDVSLFHLANHAFFKALLFLSAGSVIHAV
SNE-QDMRRMG--SLLKFMPLTYSVMLIGTLALIGFPF------LTGFYSKDFILELTQI
SSYSNLQMSYISFACWLGTMSVFFTSFYSFRLIYLTFLNNTNLAKS--------------
-SLNLVHESSLLMIFPLIILSIGSIFAGYLIRDLFVG-------------------SG--
---------------------------------SDFWGAAIFILPKHSTFIEAEEL--PI
VVKWLPFILSLLGIFFASFVQIFLKTFYFKSNLQNLLS--FFTFLINKK-WYWDVLYNRL
IVLPILNFGYSISFKILDRGFIELSGPYGFTKFVSFWS-QILIKLQTGQITHYLFFMIF-
--TFCSFSIILVYSYIN--LTFNLLLLFFTLFFFI------------
*

>P1;nad5_drome

------------------------------------------------------------
-------------------MCSISFVNLISMSLSCFLLSLYFLLNDMIYFIEWELVSLNS
MSIVMTFLFDWMSLLFMSFVLMISSLVIFYSKEYMMNDN-------HINRFIMLVLMFVL
SMMLLIISPNLISILLGWDGLGLVSYCLV-IYFQNIKSYNAGMLTALSNRIGDVALLLSI
AWMLN-YGSWNYIFYLEIMQN--------------EFEMLMIGSLVMLAAMTKSAQIPFS
SWLPAAMAAPTPVSALVHSSTLVTAGVYLLIRFNIILSTSWLG-QLMLLLSGLTMFMAGL
GANFEFDLKKIIALSTLSQLGLMMSILSMGFLKLAMFHLLTHALFKALLFMCAGAIIHNM
NNS-QDIRLMGGLSIGIHMPLTSACFNVSNLALCGMPF------LAGFYSKDMILEIV--
--SISNVN---MFSFFLYYFSTGLTVSYSFRLVYYSMTGDLNCG----------------
-SLNMLNDESWIMLRGMMGLLIMSIIGGSMLNWLIFP-----------------------
-------------------------------------FPYMICLP--------------I
YMKLLTLFVCIVGGLFGY-L--ISLSNLFFLNKSLFMY--NLSTFLGSM-WFMPYISTYG
MIFYPLNYG-QLVVKSFDQGWSEYFGGQHLYQKLSMYS-KTLFLMHNNSLKIYLLLFVFW
I---LILLILLFL----------------------------------
*

>P1;nad5_human

-------------MTMHTTMTTLTLTSLIPPILTTLVNPN--------------KK----
------------NSYPHYVKSIVASTFIISLFPTTMFMC-LDQEVIISNWH-WATTQT--
TQLSLSFKLDYFSMMFIPVALFVTWSIMEFSLWYMNSDP-------NINQFFKYLLIFLI
TMLILVTANNLFQLFIGWEGVGIMSFLLISWWYARADANTAAIQAILYNRIGDIGFILAL
AWFILHSNSWDPQQMALLNAN----------------PSLTPLLGLLLAAAGKSAQLGLH
PWLPSAMEGPTPVSALLHSSTMVVAGIFLLIRFHPLAENSPLIQTLTLCLGAITTLFAAV
CALTQNDIKKIVAFSTSSQLGLMMVTIGINQPHLAFLHICTHAFFKAMLFMCSGSIIHNL
NNE-QDIRKMG--GLLKTMPLTSTSLTIGSLALAGMPF------LTGFYSKDHIIETA--
-N-MSYTN---AWALSITLIATSLTSAYSTRMILLTLTGQPRFP----------------
-TLTNINENNPTLLNPIKGLAAGSLFAGFLITNNISP-----------------------
-------------------------------------ASPFQTTI-------------PL
YLKLTALAVTFLGLLTALD----LNYLTNKLKMKSPLC---TFYFSNML-GFYPSITHRT
IPYLGLLTSQNLPLLLLDLTWLEKLLPKTIS-QHQIST-SIITSTQKGMIKLYFLSFFFP
----LILTLLLIT----------------------------------
*

>P1;nad5_ktun

------------------------------------------------------------
-------------MKMMFLSTSQATVILLSHSLLSFSTAMYTLTTNKIILLEFCFYNFNS
VTITLPILINWTTALFSAIVCYISASVMIFTKNYMSQDI-------FIKRFTWIVMLFVL
SMNLLIFIPSLATLLLGWDGLGLVSFCLV-IYYQNYKSLGAGLMTAFMNRIGDVAILLAI
SVTFS-QGHFNALFMWSTPTM--------------TLTISMI----LLAGMTKSAQLPFC
SWLPAAMAAPTPVSALVHSSTLVTAGVFLLIQFYPFLSNSHLFSTSLMIISSMTMVMAGI
SANFETDLKKIIALSTLSQLGVMMLSVSLGLFSLALFHLFTHAMFKALLFLCAGNIIHSH
NNN-QDIRKMS--HLWIQMPFSSTCFNIANLALCGFPF------MAGFYSKDVIIEMM--
--MFNQNN---FLISLNMFLATILTASYSARLSLFIFWSKMTQS----------------
-SVVSTSDEDNSIIAPLTMLAAGAITSGAVFSWLILT-----------------------
-------------------------------------PSTLPLIS--------------M
MNKLMATFATLTGAAITY--------KLFKLELKISHS--IINNFFFNM-WFMINLSNNM
TSKSSLYTG-LYTFKSLDLGWMETIGGEGLLNKIMTLT-TINQKNQSNLFNLFISLTLLS
M---LFISVTMWFT---------------------------------
*

>P1;nad5_lter

------------------------------------------------------------
-------------MLRMFNTSLVASKLMWVIFTGMLAPTLYMVHCNSTLLLEWNLFSISS
TPMMMTIILDPLGLMFSCTVVMISANILKFSTIYMKEDK-------FINRFTVLVLLFVL
SMNMLIFFPHLIILLLGWDGLGIVSFILV-IYYQNPKSLAAGMITALTNRIGDVMLLLAI
AWTLN-QGHWNILHMWAVDEN--------------MYQALVI----IIAAMTKSAQMPFS
SWLPAAMAAPTPVSALVHSSTLVTAGVFLLIRFYNFLSSVWWFTTFLLFVAVSTTLMAGL
SASSECDMKKIIALSTLSQLGMMMAAMGLGMAHMAFFHMVTHAMFKALLFVCAGSFIHSH
MHS-QDLRWMG--NLTKQMPTTTSCLIMANLALCGFPF------MSGFYSKDMIVEAS--
--LYYPHN---SLMINLILFAVGLTAFYSTRFTMCVVLSPNNCG----------------
-PYMHLE-ESNSLTSPMLLLASMSVISGSALTWILPL-----------------------
-------------------------------------KQEMMMIP--------------L
DQKLKTLMLVTLGALMSWFF--LTTTNMTKTCLYIRHP--IINYFSCTM-WFLVPLSSQF
MMKLPMYVS-HNYLKLTDQSWLELLGGQGINNVSSKAS-NIYLASLKSTP--MNYLMMSS
M---LLLVATLVAI---------------------------------
*

>P1;nad5_marpo

-------------MYLLIVILPLIGSFAAGFFGRFLGSRG--------------------
--------------VAVVTTTCVSLSSIFSCIAFYEVA--LCASACYIKIAPWIFSEL--
FDAAWGFLFDSLTVILLLVVTIVSSLVHIYSISYMSEDP-------HSPRFFCYLSIFTF
FMLMLVTGDNFIQLFLGWEGVGLASYLLINFWFTRIQANKAAIKAMLINRVGDFGLALGI
MGCFTIFQTVDFSTIFACASAFSEPHHYFLFCNMGFHAITVICILVFIGAVGKSAQIGLH
TWLPDAMEGPTPVSALIHAATMVTAGVFMIARCSPLFEYSPNALIVITFVGAMTSFFAAT
TGILQNDLKRVIAYSTCSQLGYMIFACGISNYSVSVFHLMNHACFKALLFLSAGSVIHAM
SDE-QDMRKMG--GLASLLPFTYAMMLIGSLSLIGFPF------LTGFYSKDVILELA--
YTKYTISGN---FAFWLGSVSVFFTSYYSFRLLFLTFLAPTNSFKR--------------
-DLSRCHDAPILMAIPLILLAFGSIFVGYLAKDMMIG-------------------LG--
---------------------------------TNFWANSLFILPKNEILAESEFAT-PT
IIKLIPILFSTLGSFVAYSVNFVVNPLIFALKTSTFGN--RLYCFFNKR-WFFDKVFNDF
LARSFLRFGYEVSFKALDKGAIEILGPYGISYTIRKMA-QQISKIQSGFVYHYAFVMLLG
--LTIFISVIGLWDFISFWVDNRLYFIYIVSFLFINI----------
*

>P1;nad5_metse

-------------MYILVLTVPLLGALVSGLFGRKIGEKG--------------------
--------------AGIFTSGCLIISLSWSLLIFYETT--LNFSTTYIKLWRWLDSDL--
VTAYFGLQFDSLTAVMLIVVTSISTLVHIFSTAYMDGDP-------HVPRFMSYLSLFTF
FMILLVTSDNYPQLFIGWEGVGLCSYLLINFWLTRIEANKAAIKAMLVNRVGDIGFVLAM
LAIWDQFGCLDFASVFNIVAL-----------AP-SDNTTLICLFLFIGAVGKSAQLGLH
TWLPDAMEGPTPVSALIHAATMVTAGVFLLIRSSPLLEQAPMALMVVTIVGSLTAFMAAT
IGLVQNDLKKVIAYSTCSQLGYMVMACGLSQYSISLFHLMNHAFFKALLFLSAGSVIHAL
ADE-QDMRKMG--GLIRSIPFTYTMIVIGSLSLMGFPY------LTGFYSKDLILELA--
YDQYYLA-----FAHWLGVFSALLTAAYSLRLIYLTFISNTNAKKE--------------
-VFSQAHEGSWNLTLPLILLALGSIFVGYLTKEII-------------------------
------------------------------------WSFQITLSP----------II-PT
SIKLMPVIFSLFGAGTAVVLYHYSSR-IFNAPTSPVGL--AGYTFLYSA-WQFNYIINHF
LVQNVWRLGHLITFRVLDKGVLELIGPKGISQFMIRLT-QEISNLQSGLVYNYALMIL--
-----------------------------------------------
*

>P1;nad5_picca

--------------MMLFMTLPLLNVMMSGLLSRYMGVNN--------------------
----------------MKRLNMMNLFMMLMLLMYYYMNMIKTDNEYTLKMMEWMNMEY--
LNMNYSFNLDLLSMTMLMPMMLMSLMVNMFAWEYMKDDS-------HNPRFYTYLALFTL
FMMMLVLGDNYLMLFLGWEYMGMASFLLMGFWYNNMDNIKSSLNALFINKMGDMFFMMAL
MYLMYMYKSLNYSLMFSLVSY------------MNMDINNIIMLCLVMAASAKSAQFGLH
NWLMWAMAGPTPVSVLLHAATLVMAGMYLLMRSSPMLENCPNMLLFNLWLGAMTSLMSGL
MAMNSNDMKRIMALSTMSQLGMMFMSMGLSSYNLTLYHVLCHSLYKALLFMCAGTIIHSL
NNELQDIRFMG--GLLMYMPMTYMCMLMGSLSLMGLPS------LTGYYSKDIIIESS--
MGIFTMSG---LIIYWLVVLSSLLTNMYILKLIYYSFINMPQLNKYIYNSLSLNNTYSLP
FNFKFNFDKSWMAIICMIILSMGSLFMGYLLQDIYLG-------------------QG--
-----------------------------------NSINGLFIYPNNLNLIETHFAIN-I
YYKWIPMFNMFISILLIIYLYEFNYKLLYIYNNPLFYN---FYILFNTR-FLFDQMLNNY
IIRYTLYLS-KSLNSLLDKGFLYTLGPNGLNYLLNLLS-FNMIKFNTHLFNHYTIYISFS
----LLLFIYLQFDL--------------------------------
*

>P1;nad5_podan

-------------MYLSIIILPLLGCIVSGFLGRKVGVKG--------------------
--------------AQLITCSNVVITTILSILAFIEVG--FNNIPVTINLFRWIDSEW--
FNIIWGFQFDSLTVSMLIPVLIISSLVHIYSISYMSSDP-------HNQRFFSYLSLFTF
MMIILVTANNYLLMFVGWEGVGVCSYLLVSFWFTRIAANQSSISAFLANRVGDCFLTIGM
FAILWSLGNLDYSTVFSLAPY------------INSKVVLIIGICLLIGAMAKSSQVGLH
VWLPMAMEGPTPVSALIHAATMVTAGVYLLMRSSPLIEYNSTVLLLCLWLGAITTVFSSL
IGLFQQDIKKVIAYSTMSQLGMMVIAIGLSSYNVALFHLINHAFYKALLFLGAGSVIHAV
ADN-QDFRKYG--GLINFLPLTYSVMLIASLSLVAFPF------MTGFYSKDFILESA--
YGQFSFSG---VAVYIIATIGAIFTTLYSVKVLYLTFLSNPNGTRAYY------------
-NYKPALEGDLFLTLPLIILAIFSIFFGFITKDIFIG-------------------LG--
--------------------------------SNFFGDNSLFIHPTHEIMIDTEFAV-PV
LFKLLPFIFTISFSIIALTISEFLSELVIYFKLSRLGY--NIFGFFNQR-FLIELFYNKY
ITNLILDLG-GQMTKILDKGSIELFGPFGLEKGLVNFS-KNISSLSTSHVTTYALYILVA
--FILYLLYNYLSFNFLPFLIAGLTILTTI-----------------
*

>P1;nad5_prowi

MYIYSEQNYILKFMYLLVLLLPLLASIFAGLFGRYLGFRG--------------------
--------------ATLLTTSSVFLSFVISCVAFYEVA--LSGVTCSIEFMPWFLSEM--
FDASWGFYFDSLTVIMLLVITSISTLVHLYSISYMEADP-------HLPRFMSYLSIFTF
FMLMLVTSDNFLQMFFGWEGVGLASYLLINFWFTRLQASKASIKAMLVNRVGDFGLALGV
MATFSVFKTVDFYTVFALAAH--QSEAVLVFCNVEFHALTVICILLFVGAVGKSAQLGLH
TWLPDAMEGPTPVSALIHAATMVTAGVFMIARCSPLFEYAPKALVVVAIVGAMTCFFAAT
TGVVQNDLKRVIAYSTASQLGYMIFACGISQYTVGVFHLMNHAFFKALLFLSAGSVIHSL
ADQ-QDMRKMG--GMAKLLPFTFAMMSIGSFSLIGFPF------LTGFYSKDVILEVA--
FARYTWDAN---FAYLFGSVCVAFTSYYSFRLLFLTFIAPTNAYKS--------------
-TVKIAHDAPFLLALPLFLLSIGSIFVGYCAKDMMIG-------------------LG--
---------------------------------TPFWSNAIFVLPQNNVLLESEFI--PQ
STKFLPLVSTLLGAVTAYFFSIYSVNSSFALKQIGFFR--QLYSFLNKR-WYFDKVYNDY
ISANTMSFGYNVSFKALDKGFFEICGPTGIAYSFPALA-QYWSRLQSGLIYHYAVVMLLG
--LTMLVLVSSAWSVLENVLDSRILFIYAICFLFYNYYSLSFSDKQR
*

>P1;nad5_recam

-------------MYLLIVFLPLLGSITAGFFGRYLGKQG--------------------
--------------AAIITTSCVGLSSLFSMVAFYEVG--LCGSPCYLRLFNWIDSEM--
LHASWGFLFDSLTVVMLIVVTIVSSLVHLYSIGYMSHDP-------HLPRFMSYLSLFTF
FMLMLVTGDNFVQMFLGWEGVGLCSYLLINFWFTRLQANKSAIKAMIMNRIGDFGLSLGM
MAIFFTFKSVDFITVFALSPY--MTDFNIIFFNYEVHALTLICILLFVGAVGKSSQLGLH
TWLPDAMEGPTPVSALIHAATMVTAGVFLIARCSPIFEYAPTALLVVTIVGAMTAFFAAT
TGLLQNDIKRVIAYSTCSQLGYMVFACGISGYSVGMFHLMNHAFFKALLFLSAGCVIHAL
ADE-QDMRRMG--GIVKIVPFTYGMMLIGSMSLMGFPF------LTGFYSKDVILELA--
FAKYTIDGT---FAHWLGTVAAFFTAFYSFRLIYLTFLGETNSPRT--------------
-IINHAHDAPFIMAFPLMILAVGSIFVGFVMKDMMIG-------------------LG--
---------------------------------TDFWGNSLFTHPKNLTLIESEFI--PT
PIKLLPVVLSITGATLAIILNNYCARFLVDLKISSLGR--ELYSFLNKR-WYFDIVYNEY
VGRTMLWFGYNISFKTIDKGLIEILGPYGLERLVKRLT-LRVSQLQTGYIYHYAFIMLFG
--ITLIITIVGLWDYISEWTDYRLYFIYLITVLFYGYSETK------
*
