BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            FFFFFFFFFFFFFFF
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            FFFFFFFFFFFFFFF
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            FFFFFFFFFFFFFFF
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            FFFFFFFFFFFFFFF
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXX gettext(u'Image or Video') XXXXXXXX
            FFFFFFFFFFFFFFF
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            FFFFFFFFFFFFFFF
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXX gettext(u'PDF Upload') XXXXXXXX
            FFFFFFFFFFFFFFF
        XXXXXX
    XXXXXX
XXXXXX
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX