BBBB BBBB
BBBB BB
XXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXX
    XXXX XXXXXXXXXX XXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
            BB BBBBBBBB
                XX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
                XXXXXXXX
            BBBB
                XXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Click to expand image') XXXXXXXX
            BBBBB
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBB BB BBBBBBBBB
                    XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Publish') XXXXXXXX
                BBBB
                    XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Draft') XXXXXXXX
                BBBBB
            XXXXXX 
        XXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXX
            FFFF
            XXXXXX XXXXXXXXXXXXXXXX gettext(u'Pub Date') XXXXXXXX
            BB BBBBBBBBBBBBBBBB
                XXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFF  gettext(u'at')  FFFFFFFFFFFFFFFFFFFFFFFF FFXXXXXXXX
            BBBB
                XXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFF  gettext(u'at')  FFFFFFFFFFFFFFFFFFFFFFFF FFXXXXXXXX
            BBBBB
            XXXX XXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Edit Content') XXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX