BBBB BBBB
BBBB BB
XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXX
            XXXX gettext(u'Content') XXXXX
            XXXX gettext(u'Pub Date') XXXXX
            XXXX gettext(u'Views') XXXXX
            XXXX gettext(u'Comments') XXXXX
            XXXX gettext(u'Actions') XXXXX       
            XXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX  XXXXXXX XXXXXXXXXXXXXXXXX
        XXXXX
    XXXXXXXX
    XXXXXXX
        BBB BBBB BB BBBB
            XXX XXXXXXXXXXXXXXXXXXXX                                                        
                XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBB
                    XXX XXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFF  gettext(u'at')  FFFFFFFFFFFFFFFFFFFFFFFF FFXXXXXXXXXXXXX
                BBBB
                    XXX XXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFFFFFFFFFFFF  gettext(u'at')  FFFFFFFFFFFFFFFFFFFFFFFF FFXXXXXXXXXXXXX
                BBBBB
                BBB BBBBBB BB BBBBBBBBBBBBBBBBBBBB       
                    XXXXXXXXX
                    XXXXXXXXX  
                BBBBB
                    XXXXXXXXXX
                    XXXXXXXXXX 
                BBBBBB
                XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
        BBBBBB 
    XXXXXXXX
XXXXXXXX