BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX
      FFFFFFFFFFFFFFF
      XXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Business Type') XXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXX XXXXXXXXX gettext(u'Choose...') XXXXXXXXX
          XXXXXXX XXXXXXX gettext(u'E-commerce') XX gettext(u'E-commerce') XXXXXXXXX
          XXXXXXX XXXXXXX gettext(u'Restaurants and Food Services') XX gettext(u'Restaurants and Food Services') XXXXXXXXX
          XXXXXXX XXXXXXX gettext(u'Consulting') XX gettext(u'Consulting') XXXXXXXXX
          XXXXXXX XXXXXXX gettext(u'Health and Wellness') XX gettext(u'Health and Wellness') XXXXXXXXX
          XXXXXXX XXXXXXX gettext(u'IT Development Services') XX gettext(u'IT Development Services') XXXXXXXXX
          XXXXXXX XXXXXXX gettext(u'Education and Training') XX gettext(u'Education and Training') XXXXXXXXX
          XXXXXXX XXXXXXX gettext(u'Marketing and Advertising Services') XX gettext(u'Marketing and Advertising Services') XXXXXXXXX
          XXXXXXX XXXXXXX gettext(u'Beauty and Personal Care Services') XX gettext(u'Beauty and Personal Care Services') XXXXXXXXX
          XXXXXXX XXXXXXX gettext(u'Repair and Maintenance Services') XX gettext(u'Repair and Maintenance Services') XXXXXXXXX
          XXXXXXX XXXXXXX gettext(u'Logistics and Transportation Services') XX gettext(u'Logistics and Transportation Services') XXXXXXXXX
          XXXXXXX XXXXXXX gettext(u'Media Creators') XX gettext(u'Media Creators') XXXXXXXXX
        XXXXXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Brand Logo') XXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
            
        XXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX
      FFFFFFFFFFFFFFF
    XXXXXX
    XXXX XXXXXXXXXXXXXXX
      FFFFFFFFFFFFFFF
    XXXXXX
    XXXX XXXXXXXXXXXXXXX
      FFFFFFFFFFFFFFF
    XXXXXX
    XXXX XXXXXXXXXXXXXXX
      FFFFFFFFFFFFFFF
    XXXXXX
    XXXX XXXXXXXXXXXXXXX
      FFFFFFFFFFFFFFF
    XXXXXX
    XXXX XXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'City') XXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXX XXXXXXXXX gettext(u'Choose...') XXXXXXXXX
        XXXXXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX
      FFFFFFFFFFFFFFF
    XXXXXX
  XXXXXX
  XX XXXXXXXXXXXXXXXXXX gettext(u'Add your social media links') XXXX
  XXXX XXXXXXXXXXXXX
    
        BBB BBBB BB BBBBBBBBBBBB
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
            FFFFFF
            FFFFFFFFFFFFFFFF
        XXXXXX
        BBBBBB
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        
        FFFFFF
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u' Add') XXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Remove') XXXXXXXXX
  XXXXXX 
  XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXX