BBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX

XXXXXX
	XXXXXXXXXXXXXXX
    XXXX XXX XXXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXX XXXXXX XXXX XXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXX
		XXXXXXXXXX X
            XXXXXXXXXX XXXXXX
        X
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX X
            XXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXX
        X
        XXXXXX X
            XXXXXXX XXXXX
        X
        XXXXXX X
            XXXXXXX XXXXX
        X
        XXXXXXXX X
            XXXXXXXXXXXX XXXXXXXXXX XXXXXXXX
        X
        XXXXXX X
            XXXXXXX XXXXX
        X
        XXXXXX X
            XXXXXXX XXXXX
        X
        XXXXXX X
            XXXXXXX XXXXX
        X
        XXXXXX X
            XXXXXXX XXXXX
        X
        XXXXXX X
            XXXXXXX XXXXX
        X
        XXXXXX X
            XXXXXXX XXXXX
        X
        XXXXXX X
            XXXXXXX XXXXX
        X
        XXXXXXXXXX
            XXXXXXXXXXXXXXXXXX
        X
        XXXXXXXXX X
            XXXXXXXXXXXXXXXX XXXXXXXXXX
        X     
        XXXXX X
            XXXXXXX XXXXX
        X
        XXXXX X
            XXXXXXX XXXX
        X
        XXXXX X
            XXXX XXXX
        X
        XXXXX X
            XXXXXXX XXXXXXXXX
        X
        XXXXXXX X
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX XXX XXX XXXX XXXXXXXXXX
        X
        XX X
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXX XX
            XXXXXXXXXXX XXX XXXXXX XXXXXX
        X
        XXXXXXXXXXXXX X X
            XXXXXXXXXX XXXXX
            XXXXXXXX X XXXXX
            XXXXXXXXXXXX XXXXX
        X
        XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXX X
            XXXXXXXXXXXXXX X
                XXXXXXXXX XXXXXXXXX
                XXXXX XXXXXX
                XXXXXXX
            X
            XXXXX X
                XXXX XXX
                XXXXX XXXX
            X
            XXXXXXXXXXXXX X X
                XXXXXXXXXX XXXXX
            X
            XXXXX X
                XXXXXXX XXXX
            X
            XXXXXXXXXXX X
                XXXXXXXXXX XXXX XXXXXXXXXXX
                XXXXXXXXXXX XXXXXX XXXXXXXXXXX
            X
        X
        XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX X
            XXXXXXXXXXX X
                XXXXXXXXXXX XXXX
            X
        X
        XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX X
            XXXXX X
                XXXXXXX XXXX
            X 
            XXXXX X
                XXXXXXX
            X
            XXXXX X
                XXXXXXX XXXXX
            X
        X
	XXXXXXXX
XXXXXXX

XXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                        XXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXX XXX XXXXXXX XXXXXX XXXXXXXXXXXX gettext(u'Billing Notification') XXXXX
                    XXXXXX
                XXXXXX
                XXXX
                XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXX XXXXXX gettext(u'Billing details') XXXXX
                        XXX XXXXXXXXXXXXXXXX

                            XXXXX XXXXXX

                        XXXXX
                    XXXXXX
                XXXXXX
                XXXX
                XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXX
                       XX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXX gettext(u'This process will be effective within the next 24 hours.') XXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXX XXXXXX  XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX gettext(u'get all info in')  XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                        XX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXX XXX XXX XXXXXXXX XXX XXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXX X XXXXXXX XXX XXXXXX XXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXX

XXXXXXX