BBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX

XXXXXX
	XXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXX
		X X
			XXXXXXXXXXX XXXXXXXXXXX
		X

		XXXX X
			XXXXXXX XX
			XXXXXXXX XX
		X

		XXXXXXXXXXXXXXXXXXXXXXXXX X
			XXXXXX XXXXXXX XXXXXXXXXXX
			XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
		X

		XXXXXXXXXXXXXXXX X X
			XXXXXX XXXXXXXX
			XXXXXXXXXXXXXXXX XXXXX
		X

		X X
			XXXXXXXXXXXX XXXXXXX
		X

		XXXXXXXXXXXXXX
		XXXXXXXXXXXXX XXXXX X
			XXXXXXXXX XXXX
			XXXXXXXX XXXXX
			XXXXXXXXXXX XXXX
			XXXXXXXXX XXXXXXX
		X

		XXXXXXXXXXXX XXXXXXX X
			XXXXXXXX XXXXX
		X

		XXXXXX XXXXXXXXXXXXXXXXX X

			XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
			XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X
				XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
			X

			XXXXXXXXXXXX X
				XXXXXXXXXXX XXXXXXX
			X

			XXXXXXXXXXXX XX X
				XXXXXXX X XXXXX
			X

			XXXXXXXXXXXX XXXXXXXX
			XXXXXXXXXXXX X
				XXXXXX XXXX XXXXXXXXXXX
			X

			XXXXXXXXXXXX X
				XXXXXXXX XXXXX
			X

			XXXXXX XXXXXXX X
				XXXXXX XXXXX
				XXXXXXXX XXXXXX
			X

			XXXXXXXXXXXX X
				XXXXXXXXXXX XX
				XXXXXXXXXXX XX
				XXXXXXXXXX XX
				XXXXXXXXX XXXXXXX
				XXXXXXXXXX XXXX
			X

			XXXXXXXXXXXXXX
			XXXXXXXXXXXXX XXXXX X
				XXXXXXXX XXXXX XXXXXXXXXXX
				XXXXXXXXXXX XXXX XXXXXXXXXXX
			X
		X
	XXXXXXXX
XXXXXXX

XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XX XXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXX
	XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
		XXXXXXX
			XXXX
				XXXX
					XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
						XXXXXXX
							XXXX
								XXXX
									XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XX XXXXXX XXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXX
										XXXXXXX
											XXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXX
														XXXX
															XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXX XX XXXXXX XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
												XXXXX
											XXXXX
										XXXXXXXX
									XXXXXXXX
								XXXXX
							XXXXX
						XXXXXXXX
					XXXXXXXX
					XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
						XXXXXXX
							XXXX
								XXXX
									XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XX XXXXXX XXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXX
										XXXXXXX
											XXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXX
														XXXX
															XXX XXXXXXXXXXXX
																XXX XXXXXXXXXXXXXX XX XXXXXX XXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXX XX XXXXXXXXXXXXXX XXXX gettext(u'CONTROL EASE AND EFFICIENCY') XXXXX
															XXXXX
														XXXXX
													XXXXXXXX
												XXXXX
											XXXXX
										XXXXXXXX
									XXXXXXXX
								XXXXX
							XXXXX
						XXXXXXXX
					XXXXXXXX
					XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
						XXXXXXX
							XXXX
								XXXX
									XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXX
										XXXXXXX
											XXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXX
														XXXX
															XXX XXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXX XX XXXXXX XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXX XX XXXXXX XXXXXXXXXX XX XXXXXXXXXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
													XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
														XXXX
															XXX XXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXX
																	XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXX XXXXXXX XXXX XXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
																		XX XXXXXXXXXXXXXX XX XXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Payment Received') XXXXXXXXXXXXXXXXXXXX
																	XXXXXX
																XXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
													XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXX
														XXXX
															XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXX XX XXXXXX XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
													XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
														XXXX
															XXX XXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
																	XXXX XXXXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXX
																		XX XXXXXXXXXXXXXX XX XXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'He has done very well and it has translated into sales. We invite you to review your control of income and operations') XXXXX
																	XXXXXX
																XXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
													XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXX
														XXXX
															XXX XXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX gettext(u'CONSOLE') XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
												XXXXX
											XXXXX
										XXXXXXXX
									XXXXXXXX
								XXXXX
							XXXXX
						XXXXXXXX
					XXXXXXXX
					XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX
						XXXXXXX
							XXXX
								XXXX
									XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XX XXXXXX XXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXX
										XXXXXXX
											XXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXX
														XXXX
															XXX XXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX 


XXXXXXXXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
													XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
														XXXX
															XXX XXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXX XXXXXXX XXXX XXXXXXXXX XXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																	XX XXXXXXXXXXXXXX XXXX gettext(u'Stela Control Dynamic is the business solution that allows you to have full control of your business') XXXX
																XXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
													XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXX
														XXXX
															XXX XXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXX X
    XXXXXXXX XXXXX
    XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXXXXXX XXXXX
  X

  XXXXXXXXXXX X X
    XXXXXXXXXXXX XXXXX XXX XXXXXXXX XXXX XXXXX
    XXXXXXXXXXXXX XXXXX
    XXXXXXX XXXXXXXX
    XXXXXX XXXXXX
    XXXXXXXXXXXXXXXX XXXXX
    
  X
XXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXX
  XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
XXXXXXXXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
													XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXX
														XXXX
															XXX XXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
																	XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXXXX
																		XXXX
																			XXX XXXXXXXXXXXXXXXX XXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX
																			XXX XXXXXXXXXXXXXXXX XXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX
																			XXX XXXXXXXXXXXXXXXX XXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX
																			XXX XXXXXXXXXXXXXXXX XXX X XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXX
																		XXXXX
																	XXXXXXXX
																XXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
													XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX
														XXXX
															XXX XXXXXXXXXXXX
																XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																	XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXX XXXX XXXX XXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXXX
																XXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
												XXXXX
											XXXXX
										XXXXXXXX
									XXXXXXXX
								XXXXX
							XXXXX
						XXXXXXXX
					XXXXXXXX
					XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXX
						XXXXXXX
							XXXX
								XXXX
									XXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXX
										XXXXXXX
											XXXX
												XXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX
													XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXX
														XXXX
															XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXX
																XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXXXX
																	XXXX
																		XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
																			XXXXXXX XXXXXXXXXXX
																			XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
																				XXXX
																					XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXX XXXXXXX X XXXXX XXXXXXX XXXXXXXXXXXXX
																					XXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
																				XXXXX
																			XXXXXXXX
																		XXXXX
																	XXXXX
																XXXXXXXX
															XXXXX
														XXXXX
													XXXXXXXX
												XXXXX
											XXXXX
										XXXXXXXX
									XXXXXXXX
								XXXXX
							XXXXX
						XXXXXXXX
					XXXXXXXX
				XXXXX
			XXXXX
		XXXXXXXX
	XXXXXXXXXXXX XXX XXX
XXXXXXX

XXXXXXX