BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX
        
        FFFFFF
        XXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX gettext(u'About Section') XXXXX
        XXXX XXXXXXXXXXXXXXXXX
            
                BBB BBBB BB BBBBBBB
                XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    FFFFFF
                    FFFFFFFFFFFFFFFF
                XXXXXX
                BBBBBB
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                
                FFFFFF
            XXXXXX
        XXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXX gettext(u'Send')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX      
            XXXXXX
        XXXXXX
    XXXXXX    
XXXXXXX