# coding: utf-8

"""
    Cirro Data

    Cirro Data Platform service API

    The version of the OpenAPI document: latest
    Contact: support@cirro.bio
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class Status(str, Enum):
    """
    Status
    """

    """
    allowed enum values
    """
    COMPLETED = 'COMPLETED'
    PENDING = 'PENDING'
    RUNNING = 'RUNNING'
    ARCHIVED = 'ARCHIVED'
    DELETED = 'DELETED'
    DELETING = 'DELETING'
    SUSPENDED = 'SUSPENDED'
    DELETE = 'DELETE'
    FAILED = 'FAILED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Status from a JSON string"""
        return cls(json.loads(json_str))


