BBBB BBBB
XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'This account is now suspended') XXXXX   
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXX gettext(u'Continue') XXXXXXXXX
XXXXXX