BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBB
BBBB BBBBBBBBB
BBBB BBBBBBBB
BBBBB BBBBBBB
    BBBBB BBBBB
    XXX XXXXXXXXXXXXXX XXXX XXXXXXXXX XXXX XXXXXX gettext(u'Custom your website') XXXXXX XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    BBBBBBBB
    BBBBB BBBBBBBBBB
    XXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'CONTROL DYNAMIC')  X  gettext(u'Content') XXXXXXXXX
    BBBBBBBB

    XXXX XXXXXXXXXXXXX
        BBBBB BBBBBBBBBBBBBBB
                
        BBBBBBBB
        BBBBB BBBBBB
            XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'New Service') XXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX  
                            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXX
                                    
                                    
                                XXXXXX 
                                XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXX
                                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Send')  XX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
                                    XXXXXX
                                XXXXXX
                            XXXXXXX
                        XXXXXX    
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Proccess data, please wait') XXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXX 
                                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX gettext(u'Are you sure?') XXXXX
                                XXXX XXXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXX

                                    XXXXXX 
                                XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'This option cannot be reversed') XXXXX   
                                    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Remove') XXXXXXXXX
                                    XXXXXX
                                XXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                    XXXXXX                   
                XXXXXX
                XXXXXX
            XXXXXX 
        BBBBBBBB
    XXXXXX
BBBBBBBB