BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBB
BBBB BBBB
BBBB BBBBBB
BBBBB BBBB
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXX XXXXXXXXXXXXX XXXXXXXXX XXX XXXX XXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XX
BBBBBBBB
BBBBB BBBBBBBBBBXXXXX XXXXXXX XXXXXXXX  gettext(u'The Power is Yours') X BBBBBBBB
BBBBB BBBBBBB
    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
BBBBBBBB
BBBBB BBBBBBBBBB 
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     
BBBBBBBB
BBBBB BBBBBB
BBBBBBBB 
BBBBB BBBB
    BBBBB BBBBBBB
    BBBBBBBB
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
    XXXXXXXX
        XXXXX XXXXXXXXXXXXXXX X XBBBBBBBB BBBBBBBBBBBBBBB BBBB BBBBBBBXX 
        XXXXX XXXXXXXXXXXXXX X XBBBBBBBB BBBBBBBBBBBBB BBBB BBBBBBBXX
        XXXXX XXXXXXXXXXXXXXXXX X XBBBBBBBB BBBBBBBBBBB BBBB BBBBBBBX
        XXXXX XXXXXXXXXXXXXXXXXXXXX X XBBBBBBBB BBBBBBBBBBBBBBBB BBBB BBBBBBBX
        XXXXX XXXXXXXXXXXXXXXXXXXXXX X XBBBBBBBB BBBBBBBBBBBBBBB BBBB BBBBBBBX
        XXXXX XXXXXXXXXXXXXXXXXXX X XBBBBBBBB BBBBBBBBBBBBBB BBBB BBBBBBBXX 
        XXXXX XXXXXXXXXXXXXXXX X XBBBBBBBB BBBBBBBBBBB BBBB BBBBBBBXX 
        XXXXX XXXXXXXXXXXXXXXXXXX X XBBBBBBBB BBBBBBBBBBBBBBB BBBB BBBBBBBX 
        XXXXX XXXXXXXXXX X XBBBBBBBB BBBBBBBBBBBBBB BBBB BBBBBBBXX 
        XXXXX XXXXXXXXXXXXX X XBBBBBBBB BBBBBBBBBB BBBB BBBBBBBXX
        XXXXX XXXXXXXXXXX X XBBBBBBBB BBBBBBBBBBBBBBB BBBB BBBBBBBXX
        XXXXX XXXXXXXXXXXXXXXXX X XBBBBBBBB BBBBBBBBBBBBBBBBBB BBBB BBBBBBBXX
        XXXXX XXXXXXXXXXXXXXXXX X XBBBBBBBB BBBBBBBBBBBB BBBB BBBBBBBXX
        XXXXX XXXXXXXXXXXXXXXXXXX X XBBBBBBBB BBBBBBBBBBBBBB BBBB BBBBBBBX
        XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
        XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
        XXXXX XXXXXXX X X gettext(u'Answer Here...') X
    XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
    BBBBB BBBBBBBBBBBBBBBBB
BBBBBBBB

