BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBB
BBBB BBBBBB
BBBB BBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBBBBB
  XXXX XXXXX XXXXXXXX XXXXX XXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
          BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB
          BBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBB BB BBBBBBBBB
          BBB BBBBBBBB BB BBBBBBBBB
          BB BBBBBBBBBBBBB BB BBBBBBBBBBBBBB
              XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
          BBBBB
          BBBBBB
      XXXXXXXX      
      XXXXXX
      XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXBBBBBBBBBB
          XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
          BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
          BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB
          BBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBB BB BBBBBBBBB
          BBB BBBBBBBB BB BBBBBBBBB
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXX 
              BB BBBBBBBBBBBBB BB BBBBBBB
                  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
              BBBB BBBBBBBBBBBBB BB BBBB
                  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
              BBBBB  XXXXXXX XX
              XXXXXXXXX
          BBBBBB
      XXXXXXX
      XXXXXX
      XXXXXXXX
      XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


      XXXXXXXX XXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      X
      XXXXXXXXX
  XXXX XXXXX XXXXXXXX XXX XXXXX XXX
BBBBBBBB
BBBBB BBBBBBB  
BB BBBBBBBBBBBBBBBBBBBBBBBB

BBBB   
  XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXX
  XXXXXXX
    XXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X
  XXXXXXXX
BBBBB
      XXXX XXXXXXXXXXXXXXXXXXXXX
        BBBBB BBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXX
              XXXX
                XXXX XXXXXXXXXXXXXXXXXX
                  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXX
                      XX XXXXXXBBBBBBBB BBBBBBBBB BBBB BBBBBBBXX gettext(u'Home') XXXX 
                    XXXXXXX
                  XX XXXXXXXXXXXXXXX
                XXXXXX
                XXX XXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXX gettext(u'Website Required') XXXXXXXXX
                XXXXX
              XXXXX 
                XXXX
                  XXXX XXXXXXXXXXXXXXXXXX
                      XX XXXXXXXXXXXXXXX XXXXXXXXXXX
                      XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXX gettext(u'Communications') XXXXXXX
                    XX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXX
                  XXXXXX
                  XXX XXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXBBBBBBBB BBBBBBB BBBB BBBBBBBXX gettext(u'Inbox') XXXXXXXXX
                  XXXXX
                  XXX XXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXBBBBBBBB BBBBBBBBB BBBB BBBBBBBXX gettext(u'Support Center') XXXXXXXXX
                  XXXXX
                  XXX XXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXBBBBBBBB BBBBBB BBBB BBBBBBBXX gettext(u'Postulations') XXXXXXXXX
                  XXXXX
                  XXX XXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXBBBBBBBB BBBBBBBBBBBBBB BBBB BBBBBBBXX gettext(u'Comments') XXXXXXXXX
                  XXXXX
                XXXXX  
                  XXXX 
                    XXXX XXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXX gettext(u'Content') XXXXXXX
                      XX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXX
                    XXXXXX
                    XXX XXXXXXXXXXXXXXXXX
                      XXXXXX XXXXXXBBBBBBBB BBBBBBB BBBB BBBBBBBXX gettext(u'PRO-Stela Chat') XXXXXXXXX  
                      XXXXXX XXXXXXBBBBBBBB BBBBBBBBBBBBBB BBBB BBBBBBBXX gettext(u'Site Content Editor') XXXXXXXXX
                    XXXXX
                  XXXXX  
                  XXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXX
                    XXXXXX
                    XXX XXXXXXXXXXXXXXXXX
                      XXXXXX XXXXXXBBBBBBBB BBBBBBBBBBBBBBBBB BBBB BBBBBBBXX gettext(u'Email Marketing') XXXXXXXXX
                    XXXXX
                    XXX XXXXXXXXXXXXXXXXX
                      XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Organizer')  XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'soon') XXXXXXXXXXXXXXXXX
                    XXXXX
                  XXXXX
                  XXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXX gettext(u'Inventory') XXXXXXX
                      XX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXX
                    XXXXXX
                    XXX XXXXXXXXXXXXXXXXX
                      XXXXXX XXXXXXBBBBBBBB BBBBBBBBB BBBB BBBBBBBXX gettext(u'Services') XXXXXXXXX
                      XXXXXX XXXXXXBBBBBBBB BBBBBBBBBBB BBBB BBBBBBBXX gettext(u'Resources') XXXXXXXXX
                    XXXXX
                  XXXXX
                  XXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                      XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXX gettext(u'Finances') XXXXXXX
                      XX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXX
                    XXXXXX
                    XXX XXXXXXXXXXXXXXXXX
                      XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Payments') XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'soon') XXXXXXXXXXXXXXXXX
                      XXXXXX XXXXXXBBBBBBBB BBBBBBBBB BBBB BBBBBBBXX gettext(u'Billings') XXXXXXXXX
                    XXXXX
                  XXXXX
                  XXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                      XX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXX gettext(u'Operations') XXXXXXX
                      XX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXX
                    XXXXXX
                    XXX XXXXXXXXXXXXXXXXX
                      XXXXXX XXXXXXBBBBBBBB BBBBBBBBBBBBBBBBB BBBB BBBBBBBXX gettext(u'Booking') XXXXXXXXX
                      XXXXXX XXXXXXBBBBBBBB BBBBBBBBB BBBB BBBBBBBXX gettext(u'Reviews') XXXXXXXXX
                    XXXXX
                  XXXXX
                  XXXX 
                    XXXX XXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXXXXXXX gettext(u'Users') XXXXXXX
                      XX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXX
                    XXXXXX
                    XXX XXXXXXXXXXXXXXXXX
                      XXXXXX XXXXXXBBBBBBBB BBBBBBB BBBB BBBBBBBXX gettext(u'Users') XXXXXXXXX
                    XXXXX
                  XXXXX
                  XXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                      XXXXXX
                      XXXX XXXXXXXXXXXXXXXXX
                        BB BBBBBBBBBBBBBB
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        BBBB
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        BBBBB
                        XXXX XXXXXXXXXXXX 
                          XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Profile') XXXX
                        XXXXXX
                      XXXXXXXX XXXXXXBBBBBBBB BBBBBBBB BBBB BBBBBBBXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX gettext(u'Log Out') XXXXXXXXXXXXXXXX
                    XXXXXX
              XXXXX
            XXXXX
          XXXXXX
        BBBBBBBB
              XXXX XXXXXXXXXXXXXXXXX
                BBBBB BBBBBBBBBBBBBB
                  XXXX XXXXXXXXXX XXXXXX XXXXXX
                      XXXX XXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX gettext(u'Stela Menu') XXXXXXX
                      XXXXXX
                      XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
                      XXXXXX
                      BBBBB BBBBBBBBBBBBBBB
                      BBBBBBBB
                  XXXXXX
                BBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                      BBBBB BBBBBBB
                              XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
                                  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                                    BBBBB BBBBB
                                      XXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXX gettext(u'Hello') X FFFFFXXXXX
                                    BBBBBBBB 
                                  XXXXXX
                                  XXXX XXXXXXXXXXXXXXXXX
                                      BBBBB BBBBBBBBBBXXX XXXXXXXXXXXXXX XXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Welcome') X XX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXBBBBBBBB 
                                  XXXXXX
                              XXXXXX
                              BBBBB BBBBBBBBBBBBBBB
                                XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
                                  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                                    XXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXX gettext(u'Dashboard under construction.') XXXXX
                                    XXXX XXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXX XXXXXXX
                                  XXXXXX
                                XXXXXX
                              BBBBBBBB
                      BBBBBBBB
                XXXXXX
              XXXXXX
      XXXXXX 
BBBBBBBB

