BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBB
BBBB BBBBBB
BBBB BBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBBBBB
  XXXX XXXXX XXXXXXXX XXXXX XXXXX XXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
          BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB
          BBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBB BB BBBBBBBBB
          BBB BBBBBBBB BB BBBBBBBBB
          BB BBBBBBBBBBBBB BB BBBBBBBBBBBBBB
              XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
          BBBBB
          BBBBBB
      XXXXXXXX      
      XXXXXX
      XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXBBBBBBBBBB
          XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
          BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
          BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB
          BBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBB BB BBBBBBBBB
          BBB BBBBBBBB BB BBBBBBBBB
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXX 
              BB BBBBBBBBBBBBB BB BBBBBBB
                  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              BBBB BBBBBBBBBBBBB BB BBBB
                  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              BBBBB  XXXXXXX XX
              XXXXXXXXX
          BBBBBB
      XXXXXXX
      XXXXXX
      XXXXXXXX
      XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


      XXXXXXXX XXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      X
      XXXXXXXXX
  XXXX XXXXX XXXXXXXX XXX XXXXX XXX
BBBBBBBB
BBBBB BBBBBBB  
BB BBBBBBBBBBBBBBBBBBBBBBBB
  XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXX
BBBB   
  
BBBBB
XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
  XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXX XXXXXX XXX XXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXX XXXXXXXXXXXXXX
               XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXX
          XXXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX gettext(u'Welcome to Stela Control Dynamic') XXXXX
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXX
              XX XXXXXXXXXXXXXXXX gettext(u"We're excited to have you here. As a new user, we invite you to explore and discover all the features and benefits our system has to offer.") XXXX
              XX XXXXXXXXXXXXXX XXX XXXXX gettext(u'Before you get started, we recommend that you read our terms and conditions. This will provide you with a clear understanding of how we operate and how we can work together.') XXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBB BB BBBBBBB
                  XXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX XX XXX XXXX XXXXXX XXXXXXX XXXXXXXXXXXXX
                  XXXX
                    XXXX
                      XXXXXXXXXXXXXXXX XX XXX XXXXXXXXXXXX XX XXXXXXX X XXXXXXXX XX XXXXXXX XXX XXXXXX XXXXXXX XXXXXXXX XXX XXXXXXXXX XX XXXXXXXXXXX XXXXX XXX XXXXXXXXXX XXXXXX XXXXXXX XXX XXXXXXXXX XXXXXXXX X XXXXXXXXXXX XXXX XXXXXXXXXXXX XX XX XXXX XX XXXXXXX XXX XXXXX XXXXXXXXX XXX XXXXX XX XXXXXXX XX XXXXXXXXXXXX
                    XXXXX
                    XXXX
                      XXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX XX XXXXXXX XX XXX XXXXXXXXXXX XX XXXXXXX XX XXXXXXXXXX XXX XXXXXXXX XXXXX XXX XXXXXXX XX XXXXXXX XXXXXXXXXXX XX XXXXXXXXX XXX XXXXX XXX XXXXXXXXX XXX XXXXXXXXXXXXX XXX XXXXXXXXX X XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXX XX XXXXXXX XX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXXX
                    XXXX
                      XXXXXXXXXXXXXX XX XXXXXXXXX XXXXXXXXXXXXXXX XX XXXXXXXX XX XXXXXX XXXXXXX XXXXXXX XXXXXXXXX X XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXXX XX XXXXXXXXXX XXXXXXX XXX XXXXXXXXXXXXXX X XXXXX XXXXXXXXXX XXXX XXX XXXXX XX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XX XXXXXXXXXXX XXX XXXXXXX XXX XXXXX XXX XXXXXXX XX XXXXXXXX XXXXXXX XXXXXX XX XXXXXX XXXXXXXXXXXXX
                    XXXXX
                    XXXX
                      XXXXXXXXX XXXXXXXXXXXXXX XX XXXXXXX XX XXXXXXXXXX X XXXXXXXX XX XXXXXXX XXXXXXXXXXXXXX XXXX XXX XXXXX XXXXXXXXXX X XX XXXXXXXXXXX XXX XXXXX XXXXXXXXX XXX XXXXX XXXXXXXXXXX X XXX XXXXXX XXXXXXXXX X XXXX XXXXXXXXXXXX XX XXXXXXX XX XXXXXX XXXX XXXXXXX XXXXXXXXXX X XXXXXXXXXX XX XXXXXXX XX XXXXXXX XXXXXX XXXX XXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXX X XXXXXXXXXXXX XX XXXXXXXX XXXX XXXXXXXX XX XXXXXXX XXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX X XX XXXXXXXXXXXXXXXX
                    XXXXX
                    XXXX
                      XXXXXXXXXXXXXXXX XX XXXXXXXXX XX XXXXXXX XXXX XXXXXXXXXXX XX XX XXXXXXXXXX XX XXXXX XXXXXXXXXX XXX XXXXXXX X XXXXXXXXX XXXXXXXXXX XX XXXXXXXX XXXXXX XXXXXXX XXX XXXXX XXX XXXXX XXXXXXXXXX XX XXXXXXXXXX XX XXXXXX XX XXXXXXXXXXX XXXXXX XXX XXXXXXX XXXXXXXX XXXXXXXXXX XXXX XXXXXXXX XX XXXXXXXXXX X XXXXXXXXX XX XXX XXXXXXXXXX
                    XXXXX
                    XXXX
                      XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX XX XXXX XXXXXXXXXXX XXX XXXXXXXX X XXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXX XXX XXXXXXX XXX XXX X XXXXXXXXXXX XX XXXX XX XXXXXXXX XXXXXXX XXXXXX XX XXXXXXXXXXX XXXX XXXX XXXXXXXXX XX XX XXXXXXXXXXX XX XXXXX XXXXXXXXXX
                    XXXXX
                    XXXX
                      XXXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXX XX XXXXXXXXXXX XX XXXXXXX XX XXXXXXX XX XXXXXXXXX XXXXX XXXXXXXX XX XXXXXXXXX XXXXXXXX XX XXX XXXXXXXXXX XXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XX XXX XXXXXX XXXXXXXXXXXXX
                    XXXXX
                    XXXX
                      XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXX XXXXX XXXXXXXX X XXXXXXXXX XX XXXXXX XX XXXXXXX XX XXXXXXXXX XXXXXXX XXX XXXXXXXXXXXX XXXXX XXXXXXXXX XXX XXXXXXXXX XX XXXXXX XXXXX XX XXXXXXXXXXXXXXXXXXXX
                    XXXXX
                  XXXXX
                BBBB BBBBBBBBBBBBBB BB BBBB
                  XXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXX XX XXX XXX XXXXXX XXXXXXX XXXXXXXXXXXXX
                  XXXX
                    XXXX
                      XXXXXXXXXXXXXXXX XX XXX XXXXXXXXX XX XXXXXXXXX XXX XXXXX XXX XXX XXXXXX XXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXX XX XX XXX XXXXXXXXXX XXX XXXX XXXXXXX XXXXX XX XXXXXX XXXX XXXXX XXXXX XXX XXXXXXXXXX XXXX XXXXXXXXX XX XXX XX XXX XXXXX XXXX XXXXX XXXXXX XXXXXX XX XXX XXX XXX XXXXXXXXXXX
                    XXXXX
                    XXXX
                      XXXXXXXXXXXXXXXXX XX XXX XXXXXXXXXXX XXX XXXXXX XX X XXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXX XXXX XXXX XXXXXX XXX XXXX XX XXXXXX XXX XXXXXXX XX XXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXX XXX XXXXX XXXXXXXXXXXXXXX XXXXXXX XX XXX XXXXXXXXXX XX XXXXX XXXXXXXX XXXXXXXXXXXXXXX
                    XXXXX
                    XXXX
                      XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXX XXXXXXX XXX XXXXXX XXXXX XXXXXXX XXXXXXXXXX XXX XXX XXXXXXX XXXXXXXXXXXXX XXX XXX XXXXXXXX XX XXXXXXXXXX XXXXXXX XXXX XXXXXXXX XXX XXX XXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXX XXX XX XXX XXXXXX XX XXX XXXX XXXX XXX XXXXXXXX XXX XX XXXX XXXXXXXXXXX
                    XXXXX
                    XXXX
                      XXXXXXXXXXXXXXXX XXXXXXX XXX XXXX XXXXXX XX XXX XXX XXXXXX XXXXXXXXXXX XXX XXXXXXXXX XXXXXXXX XXX XX XXXXXXXXXX XXXX XXXXX XXXXXX XXXXXXXXXX XXXXX XXX XXXX XXXXXXXXXX XXX XXXXXXXX XXXXXXXXXX XXX XXXX XXXXX XXXX XXXX XXXXX XXXXXXX XX XXXXXXXXXX XXX XXXXXX XX XXX XXXXX XXXX XXXXXXX XXXXXXXXX XXXXXXXXXX XX XXXXXXXXXXX XXX XXXXXXX XXXX XXX XXX XXXXXX XXX XXXXXXXX XXXXXXXX XX XXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXX
                    XXXX
                      XXXXXXXXXX XXXXXXXXXXXXXX XXX XXXX XXXX XX XXXXXXXXXXX XXX XXXXXXXXXX XXX XXXXXXXX XXXX XXXXXXX XX XXXXXXX XXXXX XXX XXXXXXX XXXX XXXX XXXXXX XXXX XXX XXXXXXXXXX XXXX XXXXXXXXXX XXXXX XXX XXXXX XXXX XXXX XXXXXXXXXX XXXXXXXXX XXXXXXXX XX XXXXXX XXX XXXXXXXXX XXX XXXXXXXX XX XXX XXXXXXXXX
                    XXXXX
                    XXXX
                      XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXX XXX XXXXX XXXXX XXX XX XXXXXX XXX XXX XXXXXXXXX XXXXXXXX XXXXXXXXXXX XX XXXXXXXXXXXXX XXXXXX XX XXXXXXX XXXXXXX XXXX XXX XXX XX XXXXXXXXX XX XXX XXX XXXXXXX XXXX XX XXX XXXXX XXX XXXX XXXXXXX XX XXX XXXXXXXXXXX XX XXXX XXXXXXXXXXXX
                    XXXXX
                    XXXX
                      XXXXXXXXXXXXXXXXXXX XX XXX XXXXXXXXX XXX XXXXX XXXXXXXX XXX XXXXX XX XXXXXX XXXXX XXXXX XX XXX XXXXX XXXXXXXXX XXX XX XXX XXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XX XXX XXX XXXXXXXXXX
                    XXXXX
                    XXXX
                      XXXXXXXXXXXXXXXXXXXXX XXX XXXXX XXX XXXXXXXXX XX XXXXXXX XXXXXX XX XXX XXXXXX XXX XXX XXXX XXX XXXXXXXXXXXXXXX XXXXX XXXXXX XXXXXXX XXXXX XXXXXX XX XXXXXXXXXXXXXX
                    XXXXX
                  XXXXX
                BBBBB
            XXXXXX
            XXXX XXXXXXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXX XXXXXX
              XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXX
                  XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX gettext(u'Continue') XXXXXXXXX
                XXXXXX
              XXXXXX
              XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXX
                  XXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX gettext(u'Decline') XXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXX
                  XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX gettext(u'Accept') XXXXXXXXX
                XXXXXX
              XXXXXX
          XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXX XXXXX XXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXX
             XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX 
          XXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX gettext(u'Please fill your startup data') XXXXX
          XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              BBBBBBBBBB
              XXXX XXXXXXXXXXXXXXXXX

              XXXXXX
              XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX
                  FFFFFFFFFFFFFFF
                  XXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Business Type') XXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXX XXXXXXXX XXXXXXXXX gettext(u'Choose...') XXXXXXXXX
                      XXXXXXX XXXXXXX gettext(u'E-commerce') XX gettext(u'E-commerce') XXXXXXXXX
                      XXXXXXX XXXXXXX gettext(u'Restaurants and Food Services') XX gettext(u'Restaurants and Food Services') XXXXXXXXX
                      XXXXXXX XXXXXXX gettext(u'Consulting') XX gettext(u'Consulting') XXXXXXXXX
                      XXXXXXX XXXXXXX gettext(u'Health and Wellness') XX gettext(u'Health and Wellness') XXXXXXXXX
                      XXXXXXX XXXXXXX gettext(u'IT Development Services') XX gettext(u'IT Development Services') XXXXXXXXX
                      XXXXXXX XXXXXXX gettext(u'Education and Training') XX gettext(u'Education and Training') XXXXXXXXX
                      XXXXXXX XXXXXXX gettext(u'Marketing and Advertising Services') XX gettext(u'Marketing and Advertising Services') XXXXXXXXX
                      XXXXXXX XXXXXXX gettext(u'Beauty and Personal Care Services') XX gettext(u'Beauty and Personal Care Services') XXXXXXXXX
                      XXXXXXX XXXXXXX gettext(u'Repair and Maintenance Services') XX gettext(u'Repair and Maintenance Services') XXXXXXXXX
                      XXXXXXX XXXXXXX gettext(u'Logistics and Transportation Services') XX gettext(u'Logistics and Transportation Services') XXXXXXXXX
                      XXXXXXX XXXXXXX gettext(u'Media Creators') XX gettext(u'Media Creators') XXXXXXXXX
                    XXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Brand Logo') XXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX
                        
                    XXXXXX
                  XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'City') XXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                      XXXXXXX XXXXXXXX XXXXXXXXX gettext(u'Choose...') XXXXXXXXX
                    XXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
              XXXXXX
              XX XXXXXXXXXXXXXXXXXX gettext(u'Add your social media links') XXXX
              XXXX XXXXXXXXXXXXX
                
                    BBB BBBB BB BBBBBBBBBBBB
                    XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
                        FFFFFF
                        FFFFFFFFFFFFFFFF
                    XXXXXX
                    BBBBBB
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                    
                    FFFFFF
                XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                  XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u' Add') XXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Remove') XXXXXXXXX
              XXXXXX 
              XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Proccess data, please wait') XXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXX XXXXXX
                XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Submit')  XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX  
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
XXXXXXXX
XXXXX XXXXXXX X X gettext(u'Your address?') X
XXXXX XXXXXXXXXXX X X gettext(u'Business description') X
XXXXX XXXXXXXXX X X gettext(u'Please Upload a valid mediafile (JPG or PNG)') X
XXXXX XXXXXXXXXXXXXXXXX X X gettext(u'Please Fill all inputs in this form, Thanks') X
XXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB
