# coding: utf-8

"""
    scibec

    scibec  # noqa: E501

    The version of the OpenAPI document: 1.14.0
    Contact: klaus.wakonig@psi.ch
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from py_scibec_openapi_client import schemas  # noqa: F401


class AccessConfigWithRelations(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    (tsType: AccessConfigWithRelations, schemaOptions: { includeRelations: true })
    """


    class MetaOapg:
        required = {
            "beamlineId",
            "authEnabled",
            "usePasswords",
        }
        
        class properties:
            beamlineId = schemas.StrSchema
            authEnabled = schemas.BoolSchema
            usePasswords = schemas.BoolSchema
            id = schemas.StrSchema
            
            
            class readACL(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'readACL':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            
            
            class writeACL(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'writeACL':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            
            
            class owner(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'owner':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            createdAt = schemas.DateTimeSchema
            createdBy = schemas.StrSchema
            targetAccount = schemas.StrSchema
            
            
            class activeAccounts(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'activeAccounts':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
        
            @staticmethod
            def beamline() -> typing.Type['BeamlineWithRelations']:
                return BeamlineWithRelations
            
            
            class functionalAccounts(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['FunctionalAccountWithRelations']:
                        return FunctionalAccountWithRelations
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['FunctionalAccountWithRelations'], typing.List['FunctionalAccountWithRelations']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'functionalAccounts':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'FunctionalAccountWithRelations':
                    return super().__getitem__(i)
            __annotations__ = {
                "beamlineId": beamlineId,
                "authEnabled": authEnabled,
                "usePasswords": usePasswords,
                "id": id,
                "readACL": readACL,
                "writeACL": writeACL,
                "owner": owner,
                "createdAt": createdAt,
                "createdBy": createdBy,
                "targetAccount": targetAccount,
                "activeAccounts": activeAccounts,
                "beamline": beamline,
                "functionalAccounts": functionalAccounts,
            }
        additional_properties = schemas.NotAnyTypeSchema
    
    beamlineId: MetaOapg.properties.beamlineId
    authEnabled: MetaOapg.properties.authEnabled
    usePasswords: MetaOapg.properties.usePasswords
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["beamlineId"]) -> MetaOapg.properties.beamlineId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["authEnabled"]) -> MetaOapg.properties.authEnabled: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["usePasswords"]) -> MetaOapg.properties.usePasswords: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["readACL"]) -> MetaOapg.properties.readACL: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["writeACL"]) -> MetaOapg.properties.writeACL: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["owner"]) -> MetaOapg.properties.owner: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["createdAt"]) -> MetaOapg.properties.createdAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["createdBy"]) -> MetaOapg.properties.createdBy: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["targetAccount"]) -> MetaOapg.properties.targetAccount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["activeAccounts"]) -> MetaOapg.properties.activeAccounts: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["beamline"]) -> 'BeamlineWithRelations': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["functionalAccounts"]) -> MetaOapg.properties.functionalAccounts: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["beamlineId"], typing_extensions.Literal["authEnabled"], typing_extensions.Literal["usePasswords"], typing_extensions.Literal["id"], typing_extensions.Literal["readACL"], typing_extensions.Literal["writeACL"], typing_extensions.Literal["owner"], typing_extensions.Literal["createdAt"], typing_extensions.Literal["createdBy"], typing_extensions.Literal["targetAccount"], typing_extensions.Literal["activeAccounts"], typing_extensions.Literal["beamline"], typing_extensions.Literal["functionalAccounts"], ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["beamlineId"]) -> MetaOapg.properties.beamlineId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["authEnabled"]) -> MetaOapg.properties.authEnabled: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["usePasswords"]) -> MetaOapg.properties.usePasswords: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["readACL"]) -> typing.Union[MetaOapg.properties.readACL, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["writeACL"]) -> typing.Union[MetaOapg.properties.writeACL, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["owner"]) -> typing.Union[MetaOapg.properties.owner, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["createdAt"]) -> typing.Union[MetaOapg.properties.createdAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["createdBy"]) -> typing.Union[MetaOapg.properties.createdBy, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["targetAccount"]) -> typing.Union[MetaOapg.properties.targetAccount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["activeAccounts"]) -> typing.Union[MetaOapg.properties.activeAccounts, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["beamline"]) -> typing.Union['BeamlineWithRelations', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["functionalAccounts"]) -> typing.Union[MetaOapg.properties.functionalAccounts, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["beamlineId"], typing_extensions.Literal["authEnabled"], typing_extensions.Literal["usePasswords"], typing_extensions.Literal["id"], typing_extensions.Literal["readACL"], typing_extensions.Literal["writeACL"], typing_extensions.Literal["owner"], typing_extensions.Literal["createdAt"], typing_extensions.Literal["createdBy"], typing_extensions.Literal["targetAccount"], typing_extensions.Literal["activeAccounts"], typing_extensions.Literal["beamline"], typing_extensions.Literal["functionalAccounts"], ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        beamlineId: typing.Union[MetaOapg.properties.beamlineId, str, ],
        authEnabled: typing.Union[MetaOapg.properties.authEnabled, bool, ],
        usePasswords: typing.Union[MetaOapg.properties.usePasswords, bool, ],
        id: typing.Union[MetaOapg.properties.id, str, schemas.Unset] = schemas.unset,
        readACL: typing.Union[MetaOapg.properties.readACL, list, tuple, schemas.Unset] = schemas.unset,
        writeACL: typing.Union[MetaOapg.properties.writeACL, list, tuple, schemas.Unset] = schemas.unset,
        owner: typing.Union[MetaOapg.properties.owner, list, tuple, schemas.Unset] = schemas.unset,
        createdAt: typing.Union[MetaOapg.properties.createdAt, str, datetime, schemas.Unset] = schemas.unset,
        createdBy: typing.Union[MetaOapg.properties.createdBy, str, schemas.Unset] = schemas.unset,
        targetAccount: typing.Union[MetaOapg.properties.targetAccount, str, schemas.Unset] = schemas.unset,
        activeAccounts: typing.Union[MetaOapg.properties.activeAccounts, list, tuple, schemas.Unset] = schemas.unset,
        beamline: typing.Union['BeamlineWithRelations', schemas.Unset] = schemas.unset,
        functionalAccounts: typing.Union[MetaOapg.properties.functionalAccounts, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'AccessConfigWithRelations':
        return super().__new__(
            cls,
            *_args,
            beamlineId=beamlineId,
            authEnabled=authEnabled,
            usePasswords=usePasswords,
            id=id,
            readACL=readACL,
            writeACL=writeACL,
            owner=owner,
            createdAt=createdAt,
            createdBy=createdBy,
            targetAccount=targetAccount,
            activeAccounts=activeAccounts,
            beamline=beamline,
            functionalAccounts=functionalAccounts,
            _configuration=_configuration,
        )

from py_scibec_openapi_client.model.beamline_with_relations import BeamlineWithRelations
from py_scibec_openapi_client.model.functional_account_with_relations import FunctionalAccountWithRelations
