# Generated by Django 4.2.3 on 2024-01-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0017_chatlog_chatlogmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlogmessage',
            name='role',
            field=models.CharField(choices=[('undefined', '미정'), ('system', '시스템'), ('ai', 'ai'), ('user', 'user')], default='undefined'),
        ),
    ]
