BBBB BBBB
BBBB BBBBBBBB
BBB BBBB BB BBBBBBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX

                XXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                    FFFF
                    XXXXXXXFFFFFFFFFFFXXXXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX
                        XXXXXXX XXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXX gettext(u'Edit') XXXXXXXXX
                        XXXXXXX XXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXX gettext(u'Remove') XXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
BBBBBB