
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-22T10:58:37+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "810c05414f2204a2e30a4b177b893e7a9194cebd",
 "version": "1.21.0.post0.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
