BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX
        
        FFFFFF
        XXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX gettext(u'Variant Catalogue') XXXXX
        XXXX XXXXXXXXXXXXXXXXX
            
                BBB BBBB BB BBBBBBBB
                XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    FFFFFF
                    FFFFFFFFFFFFFFFF
                XXXXXX
                BBBBBB
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                
                FFFFFF
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX  gettext(u' Add') XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Remove') XXXXXXXXX
        XXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX gettext(u'Send')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX      
            XXXXXX
        XXXXXX
    XXXXXX    
XXXXXXX