BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBB
BBBB BBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBB
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    BBBBB BBBBBBBBBBBBBB
    BBBBBBBB
BBBBBBBB
BBBBB BBBBBBB
  BBBBB BBBBBBB
      XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXX
                XX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXX XXXXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXX XXXXX XXXXX XXXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX
                      XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX gettext(u'Proccess data, please wait') XXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX

                    XXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX gettext(u'Save')  XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXX      
                        XXXXXX
                    XXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXX
                    XXXX XXXXXXXXXXXXXXX 
                        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Are you sure?') XXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXX
    
                            XXXXXX 
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'This option cannot be reversed') XXXXX   
                            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Remove') XXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
              XXXXXX
            XXXXXX                   
          XXXXXX
        XXXXXX
    XXXXXX
  BBBBBBBB
  BBBBB BBBBBBBBBBBBBBBB
  BBBBBBBB 
BBBBBBBB
BBBBB BBBBBBBBBBBBBB
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB




