BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBBB

BBBBBBBB
BBBBB BBBBB
            XXX XXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXX gettext(u'Booking Control')  XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB
BBBBB BBBBBBBBBB
            XXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'CONTROL DYNAMIC')  X  gettext(u'Orders') XXXXXXXXX
BBBBBBBB
BBBBB BBBBBBBBBB
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX gettext(u'Remove')  XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
BBBBBBBB
BBBBB BBBBBBBBB
        XXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXX XXXXXX gettext(u'Booking List') XXXXX
BBBBBBBB

BBBBB BBBBB
    XXX XXXXXXXXXXXXX XXXXXXXXXXXX
    XXX XXXXXXXXXXXXX XXXXXX gettext(u'Customer') XXXXX
    XXX XXXXXXXXXXXXX XXXXXX gettext(u'Apointment Date') XXXXX
    XXX XXXXXXXXXXXXX XXXXXX gettext(u'Service') XXXXX
    XXX XXXXXXXXXXXXX XXXXXX gettext(u'View') XXXXX
    XXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX  XXXXXXX XXXXXXXXXXXXXXXXX          
BBBBBBBB 
BBBBB BBBBB
    BBB BBBB BB BBBBBBB
        XXXX
            XXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXX
            
            XXXXXXXXX
            XXXX
                XXXX
                    BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBB
                        XXXXXXXXX
                    BBBBBB
                XXXXX
            XXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
    BBBBBB
BBBBBBBB
BBBBB BBBBBB
BBBBBBBB
BBBBB BBBBBBBBBB
        
BBBBBBBB
BBBBB BBBBBB
    XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX 
                        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX gettext(u'Are you sure?') XXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXX

                            XXXXXX 
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'This option cannot be reversed') XXXXX   
                            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Remove') XXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            XXXXXX                   
        XXXXXX
        XXXXXX
    XXXXXX
    XXXXXXXX
        
    XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   
BBBBBBBB


