BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX
        
        FFFFFF
        XXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX gettext(u'Bulletpoints') XXXXX
        XXXX XXXXXXXXXXXXXXXXXX
            
                BBB BBBB BB BBBBBBBB
                XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX
                    FFFFFF
                    FFFFFFFFFFFFFFFF
                XXXXXX
                BBBBBB
            XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                
                FFFFFF
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX  gettext(u' Add') XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Remove') XXXXXXXXX
        XXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXX gettext(u'Send')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX      
            XXXXXX
        XXXXXX
    XXXXXX    
XXXXXXX