XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX  
    BBB BBB BB BBB
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX
        XXXXXX
        
    BBBBBB    
XXXXXX