# coding: utf-8

"""
    scibec

    scibec  # noqa: E501

    The version of the OpenAPI document: 1.14.0
    Contact: klaus.wakonig@psi.ch
    Generated by: https://openapi-generator.tech
"""

from py_scibec_openapi_client.paths.access_accounts_count.get import AccessAccountControllerCount
from py_scibec_openapi_client.paths.access_accounts.post import AccessAccountControllerCreate
from py_scibec_openapi_client.paths.access_accounts_id.delete import AccessAccountControllerDeleteById
from py_scibec_openapi_client.paths.access_accounts.get import AccessAccountControllerFind
from py_scibec_openapi_client.paths.access_accounts_id.get import AccessAccountControllerFindById
from py_scibec_openapi_client.paths.access_accounts.patch import AccessAccountControllerUpdateAll
from py_scibec_openapi_client.paths.access_accounts_id.patch import AccessAccountControllerUpdateById


class AccessAccountControllerApi(
    AccessAccountControllerCount,
    AccessAccountControllerCreate,
    AccessAccountControllerDeleteById,
    AccessAccountControllerFind,
    AccessAccountControllerFindById,
    AccessAccountControllerUpdateAll,
    AccessAccountControllerUpdateById,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
