BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBBB

BBBBBBBB
BBBBB BBBBB
            XXX XXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXX gettext(u'Services')  XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB
BBBBB BBBBBBBBBB
            XXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'CONTROL DYNAMIC')  X  gettext(u'Inventory') XXXXXXXXX
BBBBBBBB
BBBBB BBBBBBBBBB
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXX gettext(u'New Service')  XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX gettext(u'Remove')  XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
BBBBBBBB
BBBBB BBBBBBBBB
        XXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXX XXXXXX gettext(u'Services List') XXXXX
BBBBBBBB

BBBBB BBBBB
    XXX XXXXXXXXXXXXX XXXXXXXXXXXX
    XXX XXXXXXXXXXXXX XXXXXX gettext(u'Title') XXXXX
    XXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Status') XXXXX
    XXX XXXXXXXXXXXXX XXXXX gettext(u'Image') XXXXX
    XXX XXXXXXXXXXXXX XXXXXX gettext(u'Price') XXXXX
    XXX XXXXXXXXXXXXX XXXXXX gettext(u'View') XXXXX
    XXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX  XXXXXXX XXXXXXXXXXXXXXXXX          
BBBBBBBB 
BBBBB BBBBB
    BBB BBBB BB BBBBB
        XXXX
            XXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBB BB BBBBBBBB
                XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Active')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            BBBB
                XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Inactive')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            BBBBB
            XXXXXXXXX
            XXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
    BBBBBB
BBBBBBBB
BBBBB BBBBBB
BBBBBBBB
BBBBB BBBBBBBBBB
        
BBBBBBBB
BBBBB BBBBBB
    XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'New Service') XXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX  
                    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            
                            
                        XXXXXX 
                        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Send')  XX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXXX
                XXXXXX    
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Proccess data, please wait') XXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX 
                        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX gettext(u'Are you sure?') XXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXX

                            XXXXXX 
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'This option cannot be reversed') XXXXX   
                            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Remove') XXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            XXXXXX                   
        XXXXXX
        XXXXXX
    XXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   
BBBBBBBB


