BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        FFFFFFFFFFFFFFF
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        FFFFFFFFFFFFFFF
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        FFFFFFFFFFFFFFF
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        FFFFFFFFFFFFFFF
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Upload Image') XXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'upload a PDF file') XXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXX
                
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        FFFFFFFFFFFFFFF
    XXXXXX
XXXXXX
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX