BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX
        
        BBB BBBB BB BBBBBBB
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Slider Image') XXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBXXXXXXXXXXBBBBBXX
                            
                        XXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
            XXXXXX
        XXXXXX
        BBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Slider Image') XXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX
                            
                        XXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Add') XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Remove') XXXXXXXXX
    XXXXXX 
XXXXXX
XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX