BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX
        
        BBB BBBB BB BBBBBBB
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'App Image') XXXXXXX
                      XXXXXX
                      XXXX XXXXXXXXXXXXXXXXXXXX
                        
                      XXXXXX
                      XXXX XXXXXXXXXXXXXXXXXXXX
                          
                      XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        BBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'App Image') XXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX
                            
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXX
                            
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Add') XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Remove') XXXXXXXXX
    XXXXXX 
XXXXXX
XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX 