BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX
        
        BBB BBBB BB BBBBBBB
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                  XXXXXX
                XXXX XXXXXXXXXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXXX
                  FFFFFFFFFFFFFFF
                XXXXXX
            XXXXXX
        XXXXXX
        BBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
                XXXX XXXXXXXXXXXXXXX
                    FFFFFFFFFFFFFFF
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX