BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BB
BBBB BBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBBBBBBXXXXXXXXXXXBBBBBBBB
BBBBB BBBBBBBBBBBBBBBB
    XXXXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX

                    XXXX XXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
                    XXXX XXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXX
                            BBBBB BBBBBBBBBBB
                                
                            BBBBBBBB
                        XXXX
                    XXXXXXXXXX XXXXX XXX XXX

                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXX
                    XXXXXX

                    XXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXX XXXXXXXXX
                            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                                    BB BBBBBBBBBBB BB BBB
                                        XX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                                            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                                        XXXX
                                    BBBB BBBBBBBBBBB BB BBBBBBBBBB
                                        XX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                        XXXX
                                    BBBB BBBBBBBBBBB BB BBBBBBBBBBB
                                        XX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                            XX XXXXXXXXXXXXXXXXXXXXXXXXX
                                            XX XXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXX
                                    BBBB BBBBBBBBBBB BB BBBBBBBBBBB
                                        XX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                        XXXX
                                    BBBB BBBBBBBBBBB BB BBBBBBBB
                                        XX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                                            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                        XXXX
                                    BBBB BBBBBBBBBBB BB BBBBBBBBB
                                        XX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                        XXXX
                                    BBBB BBBBBBBBBBB BB BBBBBBBBBB
                                        XX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                        XXXX
                                    BBBB BBBBBBBBBBB BB BBBBBBBB
                                        XX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                                            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                            XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                        XXXX
                                    BBBBB
                                BBBBBB
                            BBBB
                                XX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                XXXX

                                XX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                                XXXX

                                XX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                XXXX

                                XX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                                XXXX

                                XX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                XXXX
                            BBBBB
                        XXXXXX
                    XXXXXX

                    XXXX XXXXXXX XXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX

                        XXX XXXXXXXXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXBBBBB BBBBBBBBBBBBBBBBXXXXXXX gettext(u'Home') XXXXXXXXXXXXXXX
                            BB BBBBBB
                                XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Our Values') XXXXXXXXXXXXXXX  
                            BBBBB
                            BB BBBBB
                                XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Staff') XXXXXXXXXXXXXXX
                            BBBBB
                            BB BBBBBBB
                                XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX gettext(u'Pricing List') XXXXXXXXXXXXXXX
                            BBBBB
                            BB BBBBB
                                BBB BBB BB BBBBB
                                    XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                            BBB BBB BB BBBBBBBBBBBBBBB
                                                XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                            BBBBBB
                                        XXXXX
                                        XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX
                                BBBBBB
                            BBBBB
                            BB BBB
                                BBB BBB BB BBB
                                    XXX XXXXXXXXXXXXXXXXXX
                                        XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                                            BBB BBB BB BBBBBBBBBBBBBBB
                                                XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                            BBBBBB
                                        XXXXX
                                        XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXX
                                BBBBBB
                            BBBBB
                            BBBBB BBBBBBB
                                XXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Load Content') XXXXXXXXX
                                XXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Load FAQ') XXXXXXXXX
                            BBBBBBBB
                            BBBBB BBBBBBBBBB
                            BBBBBBBB
                        XXXXX
                        
                    XXXXXXXXXX XXXXXXXXXXXXX XXX XXX

                XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX XXXXXXX XXX XXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            BBBBB BBBBBBBBBBBBBBBBBBBBB
        XXXXXX
    XXXXXXXXXX

    XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'New Doc') XXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX  
                    XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            
                            
                        XXXXXX 
                        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Send')  XX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXXX
                XXXXXX    
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Proccess data, please wait') XXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX 
                        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX gettext(u'Are you sure?') XXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXX

                            XXXXXX 
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'This option cannot be reversed') XXXXX   
                            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Remove') XXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            XXXXXX                   
        XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX 
                        XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX gettext(u'Are you sure?') XXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXX

                            XXXXXX 
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'This option cannot be reversed') XXXXX   
                            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Remove') XXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            XXXXXX                   
        XXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB
BBBBB BBBBBBBBB
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
BBBBBBBB
BBBBB BBBBBBBBBBBBBB
BBBBBBBB