BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBB
    XXX XXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXX gettext(u'Comments')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
BBBBBBBB
BBBBB BBBBBBBBBB
    XXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'CONTROL DYNAMIC')  X  gettext(u'Content') XXXXXXXXX
BBBBBBBB
BBBBB BBBBBBBBBB
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX gettext(u'Remove')  XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
BBBBBBBB
BBBBB BBBBBBBBB
    XXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXX XXXXXX gettext(u'Comments List') XXXXX
BBBBBBBB
BBBBB BBBBB
    XXX XXXXXXXXXXXXX XXXXXXXXXXXX
    XXX XXXXXXXXXXXXX XXXXXX gettext(u'Post') XXXXX
    XXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Status') XXXXX
    XXX XXXXXXXXXXXXX XXXXXX gettext(u'Email') XXXXX
    XXX XXXXXXXXXXXXX XXXXXX gettext(u'View') XXXXX
    XXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX  XXXXXXX XXXXXXXXXXXXXXXXX          
BBBBBBBB 
BBBBB BBBBB
    BBB BBBB BB BBBBBBBB
        XXXX
            XXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBB BB BBBBBBBBBBB
                XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Publish')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            BBBB
                XXX XXXXXXXXXXXXXXXXXXXX gettext(u'Draft')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            BBBBB
            XXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
    BBBBBB
BBBBBBBB
