BBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX

XXXXXX
	XXXXXXXXXXXXXXX
    XXXX XXX XXXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXX XXXXXXXXXX XXXXXX XXXX XXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXXXX
		XXXXXXXXXX X
            XXXXXXXXXX XXXXXX
        X
        XXXX X
            XXXXXXXXXXX XXXXXX
        X
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX X
            XXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXX XXXXXXXXX
        X
        XXXXXX
            XXXXXXXXX XXXXXXXXX
            XXXXXXXX XXXX
        X
        XXXXXXXXXX X
            XXXXXXX XXX XXXXX XXXXXX
            XXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXX XXXXXXXXX
            XXXXXXXX XXXX
        X
        XXXXXXXXXX XX X
            XXXXXXXXXX XXXXX
            XXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXX
            XXXXXX XXXXXXXX
        X
        XXXXXXXXXX X
            XXXXXX XXXXX
        X
        XXXXXX X
            XXXXXXX XXXXX
        X
        XXXXXX X
            XXXXXXX XXXXX
        X
        XXXXXXXX X
            XXXXXXXXXXXX XXXXXXXXXX XXXXXXXX
        X
        XXXXXX X
            XXXXXXX XXXXX
        X
        XXXXXX X
            XXXXXXX XXXXX
        X
        XXXXXX X
            XXXXXXX XXXXX
        X
        XXXXXX X
            XXXXXXX XXXXX
        X
        XXXXXXXXX X
            XXXXXXXX XXXXX
            XXXXXXXXXX XXXXX
          X
          XXXXXXXXX XXX
            XXXXXXXXXXXXX XXXXX
          X
        XXXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXX
            XXXXXXX XXXXX XXX XXXXXXXX
            XXXXXXXXXXX XXX XXX XXX XXXXXXXXXX
            XXXXXXXXXXX XXX XXX XXXXXXXXXXXX
        X
        XXXXXXXXXXXXXXXXXXX X
            XXXXXX XXXXX
        X
        XXXXXX X
            XXXXXXX XXXXX
        X
        XXXXXX X
            XXXXXXX XXXXX
        X
        XXXXXX X
            XXXXXXX XXXXX
        X
        XXXXXXXXXX
            XXXXXXXXXXXXXXXXXX
        X
        XXXXXXXXX X
            XXXXXXXXXXXXXXXX XXXXXXXXXX
        X    
        XXXXXXXXXX X
            XXXXXXXXXXX XXXXX
        X 
        XXXXX X
            XXXXXXX XXXXX
        X
        XXXXX X
            XXXXXXX XXXX
        X
        XXXXX X
            XXXX XXXX
        X
        XXXXX X
            XXXXXXX XXXXXXXXXX
            XXXXXXXX XXX
            XXXX XX
            XXXXX XX
        X
        XXXXXXX X
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXX XXXXXXXXX
            XXXXXXXX XXXX
        X
        XXXXXXXXXXXXX
            XXXXXXXXXXX XXX XXX XXXX XXXXXXXXXX
            XXXXXXXXX XXXXXXXXX
            XXXXXXXX XXXX
        X
        XX X
            XXXXXXXXXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXX XX
            XXXXXXXXXXX XXX XXXXXX XXXXXX
        X
        XXXXXXXXXXXXX X X
            XXXXXXXXXX XXXXX
            XXXXXXXX X XXXXX
            XXXXXXXXXXXX XXXXX
        X
        XXXXXXXXXXXX X
            XXXXXXXXXXX XXXXXXXX
        X
        XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXX X
            XXXXXXXXXXXXXX X
                XXXXXXXXX XXXXXXXXX
                XXXXX XXXXXX
                XXXXXXX
            X
            XXXXX X
                XXXX XXX
                XXXXX XXXX
            X
            XXXXXXXXXXXXX X X
                XXXXXXXXXX XXXXX
            X
            XXXXX X
                XXXXXXX XXXX
            X
            XXXXXXXXXXX X
                XXXXXXXXXX XXXX XXXXXXXXXXX
                XXXXXXXXXXX XXXXXX XXXXXXXXXXX
            X
        X
        XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX X
            XXXXXXXXXXX X
                XXXXXXXXXXX XXXX
            X
        X
        XXXXXX XXXX XXXXXX XXX XXXXXXXXXXX XXXXXX XXX XXXXXXXXXXX XXXXXXX X
            XXXXX X
                XXXXXXX XXXX
            X 
            XXXXX X
                XXXXXXX
            X
            XXXXX X
                XXXXXXX XXXXX
            X
        X
	XXXXXXXX
XXXXXXX

XXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
                        XXXX gettext(u'ALL INTEGRATED RELEASE FOR YOU') XXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXX XXX XXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Project Credentials') XXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                    XXXXXX
                XXXXXX
                XXXX
                XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXX XXXXXX gettext(u'Development Report') XXXXX
                    BBB BBBB BB BBBBBBBBBBBBBBBBBBBBB
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXX gettext(u'Modules') XXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXX gettext(u'Template') XXXXX
                        XXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXX  
                            XXX XXXXXXXXXXXXXX XXX XXXXX
                                BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
                                    XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                                BBBBBB
                            XXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX
                        XXXXXX
                        XXXXXX
                    BBBBBB
                XXXXXX
                XXXX
                XXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXX XXXXXX gettext(u'Stela Access Credentials') XXXXX
                        BBB BBBB BB BBBBBBBBBBBBBB
                            XXXX
                                XXXX gettext(u'Superuser') X XXXXX
                                XXXX gettext(u'Password') X XXXXX
                            XXXXX
                        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX
                            XX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Login') XXXX
                        XXXXXX
                        BBBBBB
                    XXXXXX
                XXXXXX
                XXXX
                XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX
                        XX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXX XXX XXX XXXXXXXX XXX XXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXX  XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXX X XXXXXXX XXX XXXXXX XXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXXX

XXXXXXX