BBBB BBBB
BBBB BBBBBBBBB

BBBB BBBBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX
        BBB BBBBBBB BB BBBBBBBB
            BB BBBBBBBBBBBB BB BBBBBBBB
            BBBB
                XXXX XXXXXXXXXXXXXX XXXX BB BBBBBBBBBBBB BB BBBBBBXXXXXXXXXXXXXBBBBXXXXXXXXXXXXXXBBBBBXX
                    XXX
                        BB BBBBBBBBBBBB BB BBBBBB
                            XXXXXXXXXXXXXXX
                        BBBB BBBBBBBBBBBB BB BBBBBBBBBBB
                            XXXXXXXXXXXXXXXX XXXXXXXXXX
                        BBBBB
                            FFFFFFFFFFFFFFFF
                    XXXX
                XXXXXX
            BBBBB
        BBBBBB
        XXXX XXXXXXXXXXXXXXXXXX
    XXXXXX