BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB     
XXXX XXXXXXXXXXXXX
    
        BBB BBBB BB BBBBBBB
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
            FFFFFF
        XXXXXX
        BBBBBB
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        FFFFFF
    XXXXXX
XXXXXX
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX
    BB BBBBBBBB
        XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX  gettext(u' Add') XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Remove') XXXXXXXXX
    BBBB
        XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX  gettext(u' Add') XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Remove') XXXXXXXXX
    BBBBB
    
XXXXXX
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
BB BB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
BBBBB
BB BBBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
BBBBB
BB BBBBBBBBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
BBBBB
BB BBBBBBBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
BBBBB
BB BBBBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
BBBBB
