BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX
        
        FFFFFF
        XXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX gettext(u'Modules') XXXXX
        XXXX XXXXXXXXXXXXXXXXX
            
                BBB BBBB BB BBBBBBB
                XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    FFFFFF
                    FFFFFFFFFFFFFFFF
                XXXXXX
                BBBBBB
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                
                FFFFFF
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX  gettext(u' Add') XXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Remove') XXXXXXXXX
        XXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXX gettext(u'Send')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX      
            XXXXXX
        XXXXXX
    XXXXXX    
XXXXXXX