BBBB BBBB
XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'We have deleted the requested record') XXXXX   
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXX gettext(u'Continue') XXXXXXXXX
XXXXXX

