BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
FFFFFF
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
BB BB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
BBBBB
BB BBBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
BBBBB
BB BBBBBBBBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX
BBBBB
BB BBBBBBBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
BBBBB
BB BBBBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
BBBBB
