TEAM_ABBS = {
    "Atlanta Hawks": ['ATL'],
    "Brooklyn Nets": ['BKN', 'BRK'],
    "Boston Celtics": ['BOS'],
    "Charlotte Hornets": ['CHH', 'CHA', 'CHO'],
    "Chicago Bulls": ['CHI'],
    "Cleveland Cavaliers": ['CLE'],
    "Dallas Mavericks": ['DAL'],
    "Denver Nuggets": ['DEN'],
    "Detroit Pistons": ['DET'],
    "Golden State Warriors": ['GSW'],
    "Houston Rockets": ['HOU'],
    "Indiana Pacers": ['IND'],
    "Los Angeles Clippers": ['LAC'],
    "Los Angeles Lakers": ['LAL'],
    "Memphis Grizzlies": ['MEM'],
    "Miami Heat": ['MIA'],
    "Milwaukee Bucks": ['MIL'],
    "Minnesota Timberwolves": ['MIN'],
    "New Orleans Pelicans": ['NOP'],
    "New York Knicks": ['NYK'],
    "Oklahoma City Thunder": ['OKC'],
    "Orlando Magic": ['ORL'],
    "Philadelphia 76ers": ['PHI'],
    "Phoenix Suns": ['PHX', 'PHO'],
    "Portland Trail Blazers": ['POR'],
    "Sacramento Kings": ['SAC'],
    "San Antonio Spurs": ['SAS'],
    "Toronto Raptors": ['TOR'],
    "Utah Jazz": ['UTA'],
    "Washington Wizards": ['WAS'],
    'Seattle SuperSonics': ['SEA'],
    'Vancouver Grizzlies': ['VAN'],
    'New Jersey Nets': ['NJN'],
    'New Orleans Hornets': ['NOH'],
    'Charlotte Bobcats': ['CAB'],
    'New Orleans/Oklahoma City Hornets': ['NCH'],
}


MONTHS = ['october', 'november', 'december', 'january', 'february',
          'march', 'april', 'may', 'june', 'july', 'august', 'september']
