BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBB
    XXX XXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXX gettext(u'Support Center')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
BBBBBBBB
BBBBB BBBBBBBBBB
    XXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'CONTROL DYNAMIC')  X  gettext(u'Communications') XXXXXXXXX
BBBBBBBB
BBBBB BBBBBBBBBB
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX gettext(u'Remove')  XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
BBBBBBBB
BBBBB BBBBBBBBB
        
BBBBBBBB
BBBBB BBBBB
    XXX XXXXXXXXXXXXX XXXXXX gettext(u'Created') XXXXX
    XXX XXXXXXXXXXXXX XXXXXX gettext(u'ID Case') XXXXX
    XXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'User') XXXXX
    XXX XXXXXXXXXXXXX XXXXXX gettext(u'Subject') XXXXX
    XXX XXXXXXXXXXXXX XXXXXX gettext(u'Status') XXXXX
    XXX XXXXXXXXXXXXX XXXXXX gettext(u'View') XXXXX          
BBBBBBBB 
BBBBB BBBBB
    BBB BBBB BB BBBBB
        XXXX
            XXX XXXXXXXXXXXXXXFFFFFFFFFFFXXXXX
            XXX XXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
            BB BBBBBBBBBBB BB BBBBBBBBBBBBB
                XXXX gettext(u'In progress')  XX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
            BBBB BBBBBBBBBBB BB BBBBBB
                XXXX gettext(u'Open')  XX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
            BBBB BBBBBBBBBBB BB BBBBBBBBBB
                XXXX gettext(u'Resolved')  XX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
            BBBB
            XXXX gettext(u'Closed')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            BBBBB
            XXXXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX 
        XXXXX
    BBBBBB
BBBBBBBB
BBBBB BBBBBB
BBBBBBBB
BBBBB BBBBBBBBBB
        
BBBBBBBB
BBBBB BBBBBB
    
BBBBBBBB
BBBBB BBBBBBBBB

BBBBBBBB