BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBB
BBBB BBBB
BBBB BB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBBBB
BBBB BBBBBBBBB
BBBBB BBBBBBB
BBBBBBBB
BBBBB BBBBBB
BBBBBBBB
BBBBB BBBBB
    XXX XXXXXXXXXXXXXX XXXX XXXXXXXXX XXXX XXXXXX gettext(u'Staff') XXXXXX XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
BBBBBBBB
BBBBB BBBBBBBBBBBBBBB
        XXXXXXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                            XXX XXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                            XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXX  gettext(u'Add Staff') XXXXXXXXX
                        XXXXXX
                    XXXXXX
                    BB BBBBB
                        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                            BBB BBB BB BBBBB
                                XXXX XXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXXXX
                                        XXXX XXXXXX XXXXXXX 
                                        XXXX XXXXXXXXXXXXXXXXXXX
                                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                                                XXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                                XXXXXXXXX
                                                XXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                    XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                                XXXXXXXXX
                                            XXXXXX
                                            XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                                        XXXXXX
                                    XXXXXX
                                    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXX
                                XXXXXX
                            BBBBBB
                        XXXXXX
                    BBBB
                        XXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX
                                XX XXXXXXXXXXXXXXXXXXXX gettext(u"You don't have added staff yet") XXXX
                            XXXXXX
                        XXXXXX
                    BBBBB
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'New Staff') XXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX  
                            XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                                XXXX XXXXXXXXXXXXXXXXX
                                    
                                    
                                XXXXXX 
                                XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXXXXXXX
                                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Send')  XX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
                                    XXXXXX
                                XXXXXX
                            XXXXXXX
                        XXXXXX    
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX
                            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Proccess data, please wait') XXXXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXX 
                                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX gettext(u'Are you sure?') XXXXX
                                XXXX XXXXXXXXXXXXXXXXX
                                    XXXX XXXXXXXXXXXX
        
                                    XXXXXX 
                                XXXXXX
                                XXXX XXXXXXXXXXXXXXXXXX
                                    XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'This option cannot be reversed') XXXXX   
                                    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                                        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Remove') XXXXXXXXX
                                    XXXXXX
                                XXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                    XXXXXX                   
                XXXXXX
                XXXXXX
            XXXXXX
        XXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
BBBBBBBB
BBBBB BBBBBBBBBBBBBB
BBBBBBBB
