# Generated by Django 5.0 on 2024-01-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='alias'),
        ),
    ]
