# Generated by Django 5.0 on 2024-01-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0010_alter_player_options_player_birth_date_player_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='player',
            name='jersey_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='jersey number'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='player',
            name='primary_position',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='primary position'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='weight'),
        ),
    ]
