BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        FFFFFFFFFFFFFFF
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        FFFFFFFFFFFFFFF
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        FFFFFFFFFFFFFFF
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        FFFFFFFFFFFFFFF
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXX gettext(u'Image or Video') XXXXXXXX
        FFFFFFFFFFFFFFF
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        FFFFFFFFFFFFFFF
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXX gettext(u'PDF Upload') XXXXXXXX
        FFFFFFFFFFFFFFF
    XXXXXX
XXXXXX
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX