BBBB BBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXX
    FFFFFFFFFFFFFFF
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXX
    FFFFFFFFFFFFFFF
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXX
    FFFFFFFFFFFFFFF
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXX
    FFFFFFFFFFFFFFF
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXX
    FFFFFFFFFFFFFFF
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXX
    FFFFFFFFFFFFFFF
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXX
    FFFFFFFFFFFFFFF
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXX
    FFFFFFFFFFFFFFF
    XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXX
    FFFFFFFFFFFFFFF
XXXXXX