BBBB BBBBBBBBBBBBBBBBB
BBBB BBBB
XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        FFFFFFFFFFFFFFF
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
        FFFFFFFFFFFFFFF
    XXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Footer media') XXXXXXXXXXXXXXXX              
    FFFFFFFFFFFFFFF
XXXXXX