# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from py_scibec_openapi_client.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    ACCESSACCOUNTS_COUNT = "/access-accounts/count"
    ACCESSACCOUNTS_ID = "/access-accounts/{id}"
    ACCESSACCOUNTS = "/access-accounts"
    ACCESSCONFIGS_COUNT = "/access-configs/count"
    ACCESSCONFIGS_ID = "/access-configs/{id}"
    ACCESSCONFIGS = "/access-configs"
    AUTH_CALLBACK = "/auth/callback"
    AUTH_LOGIN = "/auth/login"
    AUTH_LOGOUT = "/auth/logout"
    BEAMLINES_COUNT = "/beamlines/count"
    BEAMLINES_ID = "/beamlines/{id}"
    BEAMLINES = "/beamlines"
    DATASETS_COUNT = "/datasets/count"
    DATASETS_ID = "/datasets/{id}"
    DATASETS = "/datasets"
    DEVICES_COUNT = "/devices/count"
    DEVICES_ID = "/devices/{id}"
    DEVICES = "/devices"
    EXPERIMENTACCOUNTS_COUNT = "/experiment-accounts/count"
    EXPERIMENTACCOUNTS_ID = "/experiment-accounts/{id}"
    EXPERIMENTACCOUNTS = "/experiment-accounts"
    EXPERIMENTS_COUNT = "/experiments/count"
    EXPERIMENTS_ID = "/experiments/{id}"
    EXPERIMENTS = "/experiments"
    FUNCTIONALACCOUNTS_COUNT = "/functional-accounts/count"
    FUNCTIONALACCOUNTS_ID = "/functional-accounts/{id}"
    FUNCTIONALACCOUNTS = "/functional-accounts"
    NXENTITIES_COUNT = "/nxentities/count"
    NXENTITIES_ENTRY = "/nxentities/entry"
    NXENTITIES_ID = "/nxentities/{id}"
    NXENTITIES = "/nxentities"
    SCANDATA_COUNT = "/scan-data/count"
    SCANDATA_MANY = "/scan-data/many"
    SCANDATA_ID = "/scan-data/{id}"
    SCANDATA = "/scan-data"
    SCANS_COUNT = "/scans/count"
    SCANS_ID = "/scans/{id}"
    SCANS = "/scans"
    SESSIONS_COUNT = "/sessions/count"
    SESSIONS_ID = "/sessions/{id}"
    SESSIONS = "/sessions"
    USERS_LOGIN = "/users/login"
    USERS_ME = "/users/me"
    USERS_USER_ID = "/users/{userId}"
    USERS = "/users"
