BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBB
BBBBB BBBBBBBBBBX XXXXX XXXXXXX XXXXXXXXBBBBBBBBXXXXXXXX
XXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXX
            XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                    BBBBB BBBBBBB
                    BBBBBBBB
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB