# Generated by Django 4.1.7 on 2023-04-26 06:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("b2_utils", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("name", "state")},
        ),
    ]
