# coding: utf-8

"""
    scibec

    scibec  # noqa: E501

    The version of the OpenAPI document: 1.14.0
    Contact: klaus.wakonig@psi.ch
    Generated by: https://openapi-generator.tech
"""

from py_scibec_openapi_client.paths.scan_data_count.get import ScanDataControllerCount
from py_scibec_openapi_client.paths.scan_data.post import ScanDataControllerCreate
from py_scibec_openapi_client.paths.scan_data_many.post import ScanDataControllerCreateMany
from py_scibec_openapi_client.paths.scan_data_id.delete import ScanDataControllerDeleteById
from py_scibec_openapi_client.paths.scan_data.get import ScanDataControllerFind
from py_scibec_openapi_client.paths.scan_data_id.get import ScanDataControllerFindById
from py_scibec_openapi_client.paths.scan_data_id.put import ScanDataControllerReplaceById
from py_scibec_openapi_client.paths.scan_data.patch import ScanDataControllerUpdateAll
from py_scibec_openapi_client.paths.scan_data_id.patch import ScanDataControllerUpdateById


class ScanDataControllerApi(
    ScanDataControllerCount,
    ScanDataControllerCreate,
    ScanDataControllerCreateMany,
    ScanDataControllerDeleteById,
    ScanDataControllerFind,
    ScanDataControllerFindById,
    ScanDataControllerReplaceById,
    ScanDataControllerUpdateAll,
    ScanDataControllerUpdateById,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
