START_GAME = "START_GAME"
DEFAULT_BATCH_SIZE = 100
DEFAULT_INTERVAL = 30_000
DEFAULT_MAX_RETRY_ATTEMPTS = 5
FLUSH_COOLDOWN = 10_000

ENV_ALLIANCE_CLIENT_ID = "ALLIANCE_CLIENT_ID"
ENV_ALLIANCE_CLIENT_SECRET = "ALLIANCE_CLIENT_SECRET"
ENV_ALLIANCE_DSN = "ALLIANCE_DSN"
ENV_ALLIANCE_GAME_ID = "ALLIANCE_GAME_ID"
