BBBB BBBB
XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX gettext(u'Cancellation request successful') XXXXX
XXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX 
XXXXXX
   
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX gettext(u'Continue') XXXXXXXXX
XXXXXX