BBBB BBBB
XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX gettext(u'This invoice is registered') XXXXX 
XXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX 
XXXXXX
 
XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Contact Support') XXXXX 
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX gettext(u'Continue') XXXXXXXXX
XXXXXX
