BBBB BBBB
XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX gettext(u'Recipt Status Updated') XXXXX
XXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX 
XXXXXX
XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX gettext(u'Your receipt is now payeed') XXXXX  
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX gettext(u'Continue') XXXXXXXXX
XXXXXX