BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
XXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX gettext(u'Color') XXXXX
FFFFFF
XXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX