BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
FFFFFF
XXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX gettext(u'Add Bulletpoints') XXXXX
XXXX XXXXXXXXXXXXX
    
        BBB BBBB BB BBBBBBB
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
            FFFFFF
            FFFFFFFFFFFFFFFF
        XXXXXX
        BBBBBB
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        
        FFFFFF
    XXXXXX
XXXXXX
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX  gettext(u' Add') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Remove') XXXXXXXXX
XXXXXX
XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
