BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
XXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX gettext(u'Sizes') XXXXX
FFFFFF
XXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX