BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
XXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX gettext(u'Variant') XXXXX
FFFFFF
XXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX