BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB
BBBB BBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBB
    XXX XXXXXXXXXXXXXX XXXX XXXXXX gettext(u'Users Control')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB
BBBBB BBBBBBBBBB
    XXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'CONTROL DYNAMIC')  X  gettext(u'Users Control') XXXXXXXXX
BBBBBBBB
BBBBB BBBBBBBBBB
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX gettext(u'Remove')  XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
BBBBBBBB
BBBBB BBBBBBBBB
        XXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXX XXXX XXXXXX gettext(u'Users List') XXXXX
BBBBBBBB
BBBBB BBBBB
    XXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
    XXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXX gettext(u'User') XXXXX
    XXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Email') XXXXX
    XXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Rol') XXXXX
    XXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXX gettext(u'Status') XXXXX
    XXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXX gettext(u'View') XXXXX
    XXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX gettext(u'Created') XXXXX                     
BBBBBBBB 
BBBBB BBBBB
        BBB BBB BB BBBBB
            BB BBBBBBBBBBBBBBBB
            
            BBBB
                XXXX
                    XXX XXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXX XXXXXXXXXXX gettext(u'Portal User')  XX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBB BB BBBB
                        XXX XXXXXXXXXXXX gettext(u'Active')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    BBBB
                        XXX XXXXXXXXXXXX gettext(u'Inactive')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    BBBBB
                    XXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXFFFFFFFFFFFXXXXX 
                XXXXX
            BBBBB
              
        BBBBBB  
BBBBBBBB
BBBBB BBBBBB
    XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'User Portal Info') XXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX  
                    XXXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXX
                            
                            
                        XXXXXX 
                        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Send')  XX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXXX
                XXXXXX    
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX gettext(u'Proccess data, please wait') XXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB
BBBBB BBBBBBBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB
