# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_grpc_service/protos/detection_instance_data_api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from global_vo_grpc_service.protos import utils_pb2 as global__vo__grpc__service_dot_protos_dot_utils__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:data_grpc_service/protos/detection_instance_data_api.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a)global_vo_grpc_service/protos/utils.proto\"?\n+CacheDetectionInstancesDataByImageIdRequest\x12\x10\n\x08image_id\x18\x01 \x01(\x05\"\x16\n\x08\x43\x61tegory\x12\n\n\x02id\x18\x01 \x01(\x05\"\x8e\x02\n\x14\x44\x65tectionInstanceAgg\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x02\x12\r\n\x05score\x18\x03 \x01(\x02\x12\r\n\x05state\x18\x04 \x01(\t\x12\x1b\n\x08\x63\x61tegory\x18\x05 \x01(\x0b\x32\t.Category\x12\x1a\n\x08geo_bbox\x18\x06 \x01(\x0b\x32\x08.GeoBbox\x12)\n\x16geo_point_shadow_start\x18\x07 \x01(\x0b\x32\t.GeoPoint\x12\'\n\x14geo_point_shadow_end\x18\x08 \x01(\x0b\x32\t.GeoPoint\x12/\n\x0b\x64\x65tected_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x84\x01\n,CacheDetectionInstancesDataByImageIdResponse\x12 \n\x0b\x63hange_type\x18\x01 \x01(\x0e\x32\x0b.ChangeType\x12\x32\n\x13\x64\x65tection_instances\x18\x02 \x03(\x0b\x32\x15.DetectionInstanceAgg\"D\n#GetDetectionInstanceDataByIdRequest\x12\x1d\n\x15\x64\x65tection_instance_id\x18\x01 \x01(\x05\"M\n$GetDetectionInstanceDataByIdResponse\x12%\n\x1d\x64\x65tection_instance_data_bytes\x18\x01 \x01(\x0c\x32\x8f\x02\n\x18\x44\x65tectionInstanceDataApi\x12\x83\x01\n$CacheDetectionInstancesDataByImageId\x12,.CacheDetectionInstancesDataByImageIdRequest\x1a-.CacheDetectionInstancesDataByImageIdResponse\x12m\n\x1cGetDetectionInstanceDataById\x12$.GetDetectionInstanceDataByIdRequest\x1a%.GetDetectionInstanceDataByIdResponse0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_grpc_service.protos.detection_instance_data_api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CACHEDETECTIONINSTANCESDATABYIMAGEIDREQUEST._serialized_start=138
  _CACHEDETECTIONINSTANCESDATABYIMAGEIDREQUEST._serialized_end=201
  _CATEGORY._serialized_start=203
  _CATEGORY._serialized_end=225
  _DETECTIONINSTANCEAGG._serialized_start=228
  _DETECTIONINSTANCEAGG._serialized_end=498
  _CACHEDETECTIONINSTANCESDATABYIMAGEIDRESPONSE._serialized_start=501
  _CACHEDETECTIONINSTANCESDATABYIMAGEIDRESPONSE._serialized_end=633
  _GETDETECTIONINSTANCEDATABYIDREQUEST._serialized_start=635
  _GETDETECTIONINSTANCEDATABYIDREQUEST._serialized_end=703
  _GETDETECTIONINSTANCEDATABYIDRESPONSE._serialized_start=705
  _GETDETECTIONINSTANCEDATABYIDRESPONSE._serialized_end=782
  _DETECTIONINSTANCEDATAAPI._serialized_start=785
  _DETECTIONINSTANCEDATAAPI._serialized_end=1056
# @@protoc_insertion_point(module_scope)
