BBBB BBBBBBBBBBBBBBBBB
XXXXXXXXXXXXXXXXXXXX
FFFFFFFFFFFFFFF
XXXXXXXXXXXXXXXXXXXXXXXXXX
FFFFFFFFFFFFFFF
XXXXXXXXXXXXXXXXXXXXXXX
FFFFFFFFFFFFFFF
XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX
        FFFFFFFFFFFFFFF
    XXXXXX
    XXXX XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXX
        FFFFFFFFFFFFFFF
    XXXXXX
XXXXXX
XXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXX
    FFFFFFFFFFFFFFF
XXXXXX
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXX