from __future__ import annotations
MAPPING_ERRANT_ACA = {
    'ADJ': 'Word Choice',
    'ADJ:FORM': 'Word Form',
    'ADV': 'Word Form',
    'CONJ': 'Linking Devices',
    'CONTR': 'Informal',
    'DET': 'Article',
    'MORPH': 'Word Form',
    'NOUN': 'Word Choice',
    'NOUN:INFL': 'Plural-Singular',
    'NOUN:NUM': 'Plural-Singular',
    'NOUN:POSS': 'Word Form',
    'ORTH': 'Spelling',
    'OTHER': 'Other',
    'PART': 'Word Form',
    'PREP': 'Preposition',
    'PRON': 'Word Form',
    'PUNCT': 'Punctuation',
    'SPELL': 'Spelling',
    'VERB': 'Word Choice',
    'VERB:FORM': 'Verb Form',
    'VERB:INFL': 'Verb Tense',
    'VERB:SVA': 'Subject Verb Agreement',
    'VERB:TENSE': 'Verb Tense',
    'WO': 'Word Order',
}
