BBBB BBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Metric type')  XXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'New Fans') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Fans Leaves') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Top Fans Country') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Top Fans Gender Age') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Top Likes Zones') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Top Unlikes Zones') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Engage Users') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Content Engage') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Negative Feedback') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'New Fans by ads') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Page Impressions') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Page Paid Impressions') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Organic Impressions') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Viral Impressions') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Nonviral Impressions') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Content Shared Posts') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Content Age Gender Impressions') XXXXXXXXX
XXXXXXXXX