BBBB BBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Last 20 Post')  XXXXXXXXXXX
    BBB BBBB BB BBBBB
        XXXXXXX XXXXXXXXXFFFF X XXXXXXXXX
    BBBBB
        XXXXXXX XXXXXXXXX gettext(u'You have no posts made') XXXXXXXXX
    BBBBBB
XXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Metric type')  XXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Video Impressions') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Video views') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Complete video views paid') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Complete video views organic') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Complete video views mixed') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Views for more 30s paid') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Views for more 30s organic') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Views for more 30s mixed') XXXXXXXXX

XXXXXXXXX