
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-22T14:04:09-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "f86596b5f3f00a14ddd0bfa0ad400c0173fd0ff3",
 "version": "4.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
