
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-19T16:09:19-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "7a254923b9be43383d132f550e654e7534c979b6",
 "version": "0.4.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
