BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
        FFFFFF
    XXXXXX
    XXXX XXXXXXXXXXXXX
        
        BBB BBBB BB BBBBBBB
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXXX
                    FFFFFF
                XXXXXX
            XXXXXX
        BBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                FFFFFF
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Add') XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Remove') XXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            FFFFFF
        XXXXXX
    XXXXXX
XXXXXX
XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX