BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBBB
BBBB BBBBBBBBB
BBBB BBBBBBBB
BBBBB BBBBBB

BBBBBBBB
BBBBB BBBBBBB
    BBBBB BBBBB
        XXX XXXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXX gettext(u'Orders')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    BBBBBBBB
    BBBBB BBBBBBBBBB
        XXX XXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX  gettext(u'CONTROL DYNAMIC')  X  gettext(u'Operations') XXXXXXXXX
    BBBBBBBB
    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX
      BB BBBBBBBBBBBBB BB BBBBBB BBBBBBBBB
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            BBB BBBB BB BBBBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXX XXXXXX
                  XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXX
                      XXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXX gettext(u'Modules') XXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXX
                      XXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXX gettext(u'Template') XXXXX
                    XXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXX
                      
                      XXXX
                        BBB BBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                          XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                        BBBBBB
                      XXXXX
                    XXXXXX
                    XXXX XXXXXXXXXXXXXX
                      XXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX
                    XXXXXX
                  XXXXXX
              XXXXXX
            BBBBBB
        XXXXXX
        XXXX XXXXXXXXXXXXXXX XXXX XXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX gettext(u'Development Path') XXXXX

          XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXX
                  XXXX gettext(u'Turn on cloud instance') XXXXX
                  XXXX gettext(u'Configure DNS') XXXXX
                  XXXX gettext(u'Create Superuser') XXXXX
                  XXXX gettext(u'Deliver Project') XXXXX
                XXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXX
                  BB BBB BBBB
                    XXXX XXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Complete') XXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Complete') XXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Complete') XXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Complete') XXXXXXXXX
                    XXXXXX
                  BBBB BBBBBBBBB BB BBBBB BB
                    XXXX XXXXXXXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Complete') XXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Complete') XXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Complete') XXXXXXXXX
                    XXXXXX
                  BBBB BBBBBBBBB BB BBBBB BB
                    XXXX XXXXXXXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Complete') XXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Complete') XXXXXXXXX
                    XXXXXX
                  BBBB BBBBBBBBB BB BBBBB BB
                    XXXX XXXXXXXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Complete') XXXXXXXXX
                    XXXXXX
                  BBBB BBBBBBBBB BB BBBBBBBBBB
                    XXXX XXXXXXXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
                  BBBBB
            XXXXXX
          XXXXXX
          BB BBB BBBB
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX gettext(u'Cloud Credencials') XXXXX
              XXXX XXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX
              XXXXXX
            XXXXXX
          BBBBB
          BB BBBBBBBBB BB BBBBB BB
                XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                  XXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX gettext(u'Project Credencials') XXXXX
                  XXXX XXXXXXXXXXXXXXXXX
                      XXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                      XXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                      XXXXXX XXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
                  XXXXXX
                XXXXXX
          BBBBB
        XXXXXX
      BBBBB
        XXXX XXXXXXXXXXXXXXX XXXX XXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXX XXXXXX
              XXXX
                XXXXXXXXXXX XXXXXXXXXXXX
                XXXXXXXXXXX XXXXXXX XXXXXXX XXXXX
                XXXXXXXXXXXXX XXXXX XXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXXXXXX
                XXXXXXXXXXXX XXXXXXXXXXXX
                XXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXX XXXX XXXXXXXXXXXXX
                XXXXXXXXXX XXXXXXXX XXXXX
                XXXXXXXXX XXXXX XXXXXXXXXXXXX
              XXXXX
              XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Get Invoice') XXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Path Control') XXXXXXXXX
              XXXXXX
          XXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB
BBBBB BBBBBBB
  XXXXXXXX
    XXX XXXXXXXXXXXX X X  gettext(u'Confirm?') X
    XXXXX XXXXXXXXX X X gettext(u'Complete Step') X
    XXXXX XXXX X X gettext(u'This option cannot be reversed!') X
    XXXXX XXXXXXX X X gettext(u'Complete') X
    XXXXX XXXXXX X X gettext(u'Cancel') X
    XXXXX XXXXXXXXXXXXX X X gettext(u'Step Complete.') X
    XXXXX XXXXXXXXXXXX X X gettext(u'Updating Data.') X
  XXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
BBBBBBBB