BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB       
XXXX XXXXXXXXXXXXX
    
        BBB BBBB BB BBBBBBB
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
            FFFFFF
            FFFFFFFFFFFFFFFF
        XXXXXX
        XXXX
        BBBBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        
        FFFFFF
    XXXXXX
XXXXXX
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u' Add') XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Remove') XXXXXXXXX
XXXXXX 
XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXX
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX