BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
XXXXXXXXXXXXXXXX XXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXX
        XXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX XXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXXXXXX
    XXXXXX
 XXXXXX 
  XXXXXX
  BBBBBBBB BBBBBBB
XXXXXXX