BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
    BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXX
        XXXXXXXXX
          XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXXXXXX
    XXXXXX
 XXXXXX 
  XXXXXX
  BBBBBBBB BBBBBBB
XXXXXXX