BBBB BBBB
BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXX gettext(u'Customer Data') XXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXX
            
            XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
        
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
        
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
        
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
         FFFFFFFFFFFFFFF
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
         FFFFFFFFFFFFFFF
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXX
        
    XXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXX gettext(u'Recipt Charges') XXXXX
                XXXX XXXXXXXXXXXXX
                    
                        BBB BBBB BB BBBBBBB
                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXX
                            
                            XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXX
                                 FFFFFFFFFFFFFFF
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXX
                                 FFFFFFFFFFFFFFF
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXX XXXXXXXXXX XXXXXXXX
                                XXXXXX XXXXXXXXXXXXX gettext(u'Delete') XXXXXXXX  FFFFFFFFFFFFFFF
                            XXXXXX
                        XXXXXX
                        BBBBBB
                    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                         FFFFFFFFFFFFFFF
                        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXX
                             FFFFFFFFFFFFFFF
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXX
                             FFFFFFFFFFFFFFF
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXX XXXXXXXXXX XXXXXXXX
                            XXXXXX XXXXXXXXXXXXX gettext(u'Delete') XXXXXXXX  FFFFFFFFFFFFFFF
                        XXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Add') XXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Remove') XXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXX gettext(u'Recipt Discounts') XXXXX
                XXXX XXXXXXXXXXXXXX
                    
                        BBB BBBB BB BBBBBBBB
                        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX
                            
                            XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXX
                                 FFFFFFFFFFFFFFF
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXX
                                 FFFFFFFFFFFFFFF
                            XXXXXX
                            XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXX XXXXXXXXXX XXXXXXXX
                                XXXXXX XXXXXXXXXXXXX gettext(u'Delete') XXXXXXXX  FFFFFFFFFFFFFFF
                            XXXXXX
                        XXXXXX
                        BBBBBB
                    XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                         FFFFFFFFFFFFFFF
                        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX
                             FFFFFFFFFFFFFFF
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX
                             FFFFFFFFFFFFFFF
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXX XXXXXXXXXX XXXXXXXX
                            XXXXXX XXXXXXXXXXXXX gettext(u'Delete') XXXXXXXX  FFFFFFFFFFFFFFF
                        XXXXXX
                    XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Add') XXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Remove') XXXXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
        XXX XXXXXXXXXXXX XXXXXXX XXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXX gettext(u'Notes') XXXXX
        XXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXXX XXXXXXXXXXXXXXXX
             FFFFFFFFFFFFFFF
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXX
                        XXXXXXXXXXX
                        XXXXXXXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX