BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Name') X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    FFFFFFFFFFFFFFF
XXXXXX

XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Subject') X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    FFFFFFFFFFFFFFF
XXXXXX

XXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Phone') X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    FFFFFFFFFFFFFFF
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXX

XXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Email') X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    FFFFFFFFFFFFFFF
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXX

XXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Message') X XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    FFFFFFFFFFFFFFF
XXXXXX