WAIT_TIMEOUT = 5
MAX_RECURSION_COUNT = 3

NOPECHA_API_KEY = "NOPECHA_API_KEY"
GOOGLE_RECAPTCHA_PAGE_URL = "le.com/recaptcha/api2/demo"


CAPTCHA_TYPE_RECAPTCHA = 'recaptcha'
CAPTCHA_TYPE_TEXTCAPTCHA = 'textcaptcha'
