BBBB BBBB
BBBB BBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
        FFFFFF
    XXXXXX
    XXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX gettext(u'Add Social Links') XXXXX
    XXXX XXXXXXXXXXXXX
        
        BBB BBBB BB BBBBBBB
            XXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXXX
                    FFFFFF
                XXXXXX
            XXXXXX
        BBBBBB
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                FFFFFF
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Add') XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX  gettext(u'Remove') XXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            FFFFFF
        XXXXXX
    XXXXXX
XXXXXX
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX
BB BB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX
BBBBB