BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBBBBBBX XX XXXXXXX XXXXX XXXXXXXXXBBBBBBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXX
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBB
                    BBB BBBBBBB BB BBBBBBBB
                        XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX
                        XXXXXX
                    BBBBBB
                BBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX
               XXXXX XXXXXX XX XXXX XXXXXXXXXXXX XXXXXX XXXXXXX XXX XXXXXXXXXXXXXXX 
            XXXXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB