BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB
BBBB BBBBB
BBBBB BBBBBBBBBB XXXXX X  gettext(u'Sign In') BBBBBBBB
BBBBB BBBBBB
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB
BBBBB BBBB
    BBBBB BBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBB
                    BBB BBBBBBB BB BBBBBBBB
                        XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX
                        XXXXXX
                    BBBBBB
                BBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXX XXXXX XXXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXX XXX XXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXBBBBBBBB BBBBBBB BBBB BBBBBBBX   XXXXXXXXXXXXXX
                    BBBBBBBBBB
                    XXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    BB BBB
                    XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
                        XXXXXX  gettext(u'You are not authorized to login.')  
                    XXXXXX
                    BBBBB
                    
                    

                    
                    XXXX XXXXXXXXXXXXX XXXXXXX
                        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX
                        XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXX XXXX XXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Log In') XXXXXXXXX
                    XXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB