BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBBBBBBX XXXXX XXXXXXXXXXBBBBBBBB
BBBBB BBBBBBB
BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXXXX
        XXXXXXXXXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBBX
    XXXXXXXXX
BBBBB
XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXX
                XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBB
                    BBB BBBBBBB BB BBBBBBBB
                        XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX
                        XXXXXX
                    BBBBBB
                BBBBB
            XXXXXX
            XXXXX XXXXXXXXXXXXXXXXX XXX XXXXXXX XXXXXXXXX XXXXXXXX XXXXXXXXXXXXXX
                BBBBBBBBBB
                XXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                BB BBBBBBBBBBB
                XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXX XXXXXXXX
                XXXXXX
                BBBBB
        
                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                
                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                
                XXXX
                    XXXXXX XXXXXXXXXX XX XXXXX XXX XXXXXXX X XXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXXX XXXXXXXX XX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX
                    XXXXXX XXXXX XXX XXXXX X XXX XXXXXXXXXXXXXXX
                XXXXX
                XXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXX XXXX XXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX
            XX XXXXXXXXXXXX XXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBXXXXX XXXXXX XXX XXXXXXXXXXX
            XXXX
            XX XXXXXXXXXXXX XXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXX
            XXXX
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB