BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBBBBBBX XXXXXXXXXXX XXXXXXXXXXBBBBBBBB
BBBBB BBBBBBB  
BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXXXX
        XXXXXXXXXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBBX
    XXXXXXXXX
BBBBB
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXX
                    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBB
                        BBB BBBBBBB BB BBBBBBBB
                            XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXX
                            XXXXXX
                        BBBBBB
                    BBBBB
                XXXXXX
                XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXX XXXXXXX XXXXXXXXX XXXXXXXXX
                   XX XXXXXXXXX XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX
                        XXXXXXXXXX XX XXXXXX XXXXXXXXXXX XXXX XXXXXXXXX XX XXXXXXXXXXXXXXX
                   BB BBBBBBBBBBB
                     XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
                        XXXXXX XXXX XXXXXXXXX XX XXXXXX XX XXXX XXXXXXXXXX
                    XXXXXX
                    BBBBB 
                    BBBBBBBBBB
                    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    
                    XXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXX XXXX XXXX XXXX XXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXX
             XXXXXX
         XXXXXX
    XXXXXX
BBBBBBBB