BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBBBBBB X XXXXXXXXXXX XXXXXXXXXXBBBBBBBB
BBBBB BBBBBBB  
BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXXXX
        XXXXXXXXXXXXXXXXXXXX X XBBB BBBBBBBBBBBBBBBBBBX
    XXXXXXXXX
BBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXX XXXXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXX
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                BB BBBBBBBB
                    BBB BBBBBBB BB BBBBBBBB
                        XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXXXXXX
                        XXXXXX
                    BBBBBB
                BBBBB
            XXXXXX
            XXXX XXXXXXXXXXXX
                BB BBBBBBB BB BBBBBBBBBBBBBBBBBBBBB
                        XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX XXXXX XXXXXXXXXXXXXXX
                        XXXXXXXXX XX XXXXXX XXXX XXXXXXXXXXXXXXXXX
                BBBBB
                BB BBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB
                        XXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXX XXXXXXXXXXXX
                        XX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXXXXXXXXXXX
                BBBBB
            XXXXXX     
        XXXXXX
    XXXXXX
XXXXXX
BBBBBBBB
